/** @file properties_oracle.h @brief Independent typed SDK fixtures for the pinned Properties2 generators. */
#ifndef WaddlePropertiesOracleH
/** @brief Immutable include guard; no storage. */
#define WaddlePropertiesOracleH
#include <assert.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>
#include <vulkan/vulkan.h>
/** @brief Owned native node; selected member follows the explicit query tag. */
typedef union property_data_t {
  VkPhysicalDeviceVulkan11Properties core11; /**< Owned VkPhysicalDeviceVulkan11Properties payload, no retained links. */
  VkPhysicalDeviceVulkan12Properties core12; /**< Owned VkPhysicalDeviceVulkan12Properties payload, no retained links. */
  VkPhysicalDeviceVulkan13Properties core13; /**< Owned VkPhysicalDeviceVulkan13Properties payload, no retained links. */
  VkPhysicalDeviceRobustness2PropertiesEXT robustness; /**< Owned VkPhysicalDeviceRobustness2PropertiesEXT payload, no retained links. */
  VkPhysicalDeviceMaintenance5Properties maintenance; /**< Owned VkPhysicalDeviceMaintenance5Properties payload, no retained links. */
} property_data_t;
_Static_assert(sizeof(VkPhysicalDeviceProperties) == 824 && _Alignof(VkPhysicalDeviceProperties) == 8, "Pinned VkPhysicalDeviceProperties ABI");
_Static_assert(offsetof(VkPhysicalDeviceProperties, apiVersion) == 0 && sizeof(((VkPhysicalDeviceProperties *)0)->apiVersion) == 4, "Pinned VkPhysicalDeviceProperties.apiVersion");
_Static_assert(offsetof(VkPhysicalDeviceProperties, driverVersion) == 4 && sizeof(((VkPhysicalDeviceProperties *)0)->driverVersion) == 4, "Pinned VkPhysicalDeviceProperties.driverVersion");
_Static_assert(offsetof(VkPhysicalDeviceProperties, vendorID) == 8 && sizeof(((VkPhysicalDeviceProperties *)0)->vendorID) == 4, "Pinned VkPhysicalDeviceProperties.vendorID");
_Static_assert(offsetof(VkPhysicalDeviceProperties, deviceID) == 12 && sizeof(((VkPhysicalDeviceProperties *)0)->deviceID) == 4, "Pinned VkPhysicalDeviceProperties.deviceID");
_Static_assert(offsetof(VkPhysicalDeviceProperties, deviceType) == 16 && sizeof(((VkPhysicalDeviceProperties *)0)->deviceType) == 4, "Pinned VkPhysicalDeviceProperties.deviceType");
_Static_assert(offsetof(VkPhysicalDeviceProperties, deviceName) == 20 && sizeof(((VkPhysicalDeviceProperties *)0)->deviceName) == 256, "Pinned VkPhysicalDeviceProperties.deviceName");
_Static_assert(offsetof(VkPhysicalDeviceProperties, pipelineCacheUUID) == 276 && sizeof(((VkPhysicalDeviceProperties *)0)->pipelineCacheUUID) == 16, "Pinned VkPhysicalDeviceProperties.pipelineCacheUUID");
_Static_assert(offsetof(VkPhysicalDeviceProperties, limits) == 296 && sizeof(((VkPhysicalDeviceProperties *)0)->limits) == 504, "Pinned VkPhysicalDeviceProperties.limits");
_Static_assert(offsetof(VkPhysicalDeviceProperties, sparseProperties) == 800 && sizeof(((VkPhysicalDeviceProperties *)0)->sparseProperties) == 20, "Pinned VkPhysicalDeviceProperties.sparseProperties");
_Static_assert(sizeof(VkPhysicalDeviceLimits) == 504 && _Alignof(VkPhysicalDeviceLimits) == 8, "Pinned VkPhysicalDeviceLimits ABI");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxImageDimension1D) == 0 && sizeof(((VkPhysicalDeviceLimits *)0)->maxImageDimension1D) == 4, "Pinned VkPhysicalDeviceLimits.maxImageDimension1D");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxImageDimension2D) == 4 && sizeof(((VkPhysicalDeviceLimits *)0)->maxImageDimension2D) == 4, "Pinned VkPhysicalDeviceLimits.maxImageDimension2D");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxImageDimension3D) == 8 && sizeof(((VkPhysicalDeviceLimits *)0)->maxImageDimension3D) == 4, "Pinned VkPhysicalDeviceLimits.maxImageDimension3D");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxImageDimensionCube) == 12 && sizeof(((VkPhysicalDeviceLimits *)0)->maxImageDimensionCube) == 4, "Pinned VkPhysicalDeviceLimits.maxImageDimensionCube");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxImageArrayLayers) == 16 && sizeof(((VkPhysicalDeviceLimits *)0)->maxImageArrayLayers) == 4, "Pinned VkPhysicalDeviceLimits.maxImageArrayLayers");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxTexelBufferElements) == 20 && sizeof(((VkPhysicalDeviceLimits *)0)->maxTexelBufferElements) == 4, "Pinned VkPhysicalDeviceLimits.maxTexelBufferElements");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxUniformBufferRange) == 24 && sizeof(((VkPhysicalDeviceLimits *)0)->maxUniformBufferRange) == 4, "Pinned VkPhysicalDeviceLimits.maxUniformBufferRange");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxStorageBufferRange) == 28 && sizeof(((VkPhysicalDeviceLimits *)0)->maxStorageBufferRange) == 4, "Pinned VkPhysicalDeviceLimits.maxStorageBufferRange");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxPushConstantsSize) == 32 && sizeof(((VkPhysicalDeviceLimits *)0)->maxPushConstantsSize) == 4, "Pinned VkPhysicalDeviceLimits.maxPushConstantsSize");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxMemoryAllocationCount) == 36 && sizeof(((VkPhysicalDeviceLimits *)0)->maxMemoryAllocationCount) == 4, "Pinned VkPhysicalDeviceLimits.maxMemoryAllocationCount");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxSamplerAllocationCount) == 40 && sizeof(((VkPhysicalDeviceLimits *)0)->maxSamplerAllocationCount) == 4, "Pinned VkPhysicalDeviceLimits.maxSamplerAllocationCount");
_Static_assert(offsetof(VkPhysicalDeviceLimits, bufferImageGranularity) == 48 && sizeof(((VkPhysicalDeviceLimits *)0)->bufferImageGranularity) == 8, "Pinned VkPhysicalDeviceLimits.bufferImageGranularity");
_Static_assert(offsetof(VkPhysicalDeviceLimits, sparseAddressSpaceSize) == 56 && sizeof(((VkPhysicalDeviceLimits *)0)->sparseAddressSpaceSize) == 8, "Pinned VkPhysicalDeviceLimits.sparseAddressSpaceSize");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxBoundDescriptorSets) == 64 && sizeof(((VkPhysicalDeviceLimits *)0)->maxBoundDescriptorSets) == 4, "Pinned VkPhysicalDeviceLimits.maxBoundDescriptorSets");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxPerStageDescriptorSamplers) == 68 && sizeof(((VkPhysicalDeviceLimits *)0)->maxPerStageDescriptorSamplers) == 4, "Pinned VkPhysicalDeviceLimits.maxPerStageDescriptorSamplers");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxPerStageDescriptorUniformBuffers) == 72 && sizeof(((VkPhysicalDeviceLimits *)0)->maxPerStageDescriptorUniformBuffers) == 4, "Pinned VkPhysicalDeviceLimits.maxPerStageDescriptorUniformBuffers");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxPerStageDescriptorStorageBuffers) == 76 && sizeof(((VkPhysicalDeviceLimits *)0)->maxPerStageDescriptorStorageBuffers) == 4, "Pinned VkPhysicalDeviceLimits.maxPerStageDescriptorStorageBuffers");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxPerStageDescriptorSampledImages) == 80 && sizeof(((VkPhysicalDeviceLimits *)0)->maxPerStageDescriptorSampledImages) == 4, "Pinned VkPhysicalDeviceLimits.maxPerStageDescriptorSampledImages");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxPerStageDescriptorStorageImages) == 84 && sizeof(((VkPhysicalDeviceLimits *)0)->maxPerStageDescriptorStorageImages) == 4, "Pinned VkPhysicalDeviceLimits.maxPerStageDescriptorStorageImages");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxPerStageDescriptorInputAttachments) == 88 && sizeof(((VkPhysicalDeviceLimits *)0)->maxPerStageDescriptorInputAttachments) == 4, "Pinned VkPhysicalDeviceLimits.maxPerStageDescriptorInputAttachments");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxPerStageResources) == 92 && sizeof(((VkPhysicalDeviceLimits *)0)->maxPerStageResources) == 4, "Pinned VkPhysicalDeviceLimits.maxPerStageResources");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxDescriptorSetSamplers) == 96 && sizeof(((VkPhysicalDeviceLimits *)0)->maxDescriptorSetSamplers) == 4, "Pinned VkPhysicalDeviceLimits.maxDescriptorSetSamplers");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxDescriptorSetUniformBuffers) == 100 && sizeof(((VkPhysicalDeviceLimits *)0)->maxDescriptorSetUniformBuffers) == 4, "Pinned VkPhysicalDeviceLimits.maxDescriptorSetUniformBuffers");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxDescriptorSetUniformBuffersDynamic) == 104 && sizeof(((VkPhysicalDeviceLimits *)0)->maxDescriptorSetUniformBuffersDynamic) == 4, "Pinned VkPhysicalDeviceLimits.maxDescriptorSetUniformBuffersDynamic");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxDescriptorSetStorageBuffers) == 108 && sizeof(((VkPhysicalDeviceLimits *)0)->maxDescriptorSetStorageBuffers) == 4, "Pinned VkPhysicalDeviceLimits.maxDescriptorSetStorageBuffers");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxDescriptorSetStorageBuffersDynamic) == 112 && sizeof(((VkPhysicalDeviceLimits *)0)->maxDescriptorSetStorageBuffersDynamic) == 4, "Pinned VkPhysicalDeviceLimits.maxDescriptorSetStorageBuffersDynamic");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxDescriptorSetSampledImages) == 116 && sizeof(((VkPhysicalDeviceLimits *)0)->maxDescriptorSetSampledImages) == 4, "Pinned VkPhysicalDeviceLimits.maxDescriptorSetSampledImages");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxDescriptorSetStorageImages) == 120 && sizeof(((VkPhysicalDeviceLimits *)0)->maxDescriptorSetStorageImages) == 4, "Pinned VkPhysicalDeviceLimits.maxDescriptorSetStorageImages");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxDescriptorSetInputAttachments) == 124 && sizeof(((VkPhysicalDeviceLimits *)0)->maxDescriptorSetInputAttachments) == 4, "Pinned VkPhysicalDeviceLimits.maxDescriptorSetInputAttachments");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxVertexInputAttributes) == 128 && sizeof(((VkPhysicalDeviceLimits *)0)->maxVertexInputAttributes) == 4, "Pinned VkPhysicalDeviceLimits.maxVertexInputAttributes");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxVertexInputBindings) == 132 && sizeof(((VkPhysicalDeviceLimits *)0)->maxVertexInputBindings) == 4, "Pinned VkPhysicalDeviceLimits.maxVertexInputBindings");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxVertexInputAttributeOffset) == 136 && sizeof(((VkPhysicalDeviceLimits *)0)->maxVertexInputAttributeOffset) == 4, "Pinned VkPhysicalDeviceLimits.maxVertexInputAttributeOffset");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxVertexInputBindingStride) == 140 && sizeof(((VkPhysicalDeviceLimits *)0)->maxVertexInputBindingStride) == 4, "Pinned VkPhysicalDeviceLimits.maxVertexInputBindingStride");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxVertexOutputComponents) == 144 && sizeof(((VkPhysicalDeviceLimits *)0)->maxVertexOutputComponents) == 4, "Pinned VkPhysicalDeviceLimits.maxVertexOutputComponents");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxTessellationGenerationLevel) == 148 && sizeof(((VkPhysicalDeviceLimits *)0)->maxTessellationGenerationLevel) == 4, "Pinned VkPhysicalDeviceLimits.maxTessellationGenerationLevel");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxTessellationPatchSize) == 152 && sizeof(((VkPhysicalDeviceLimits *)0)->maxTessellationPatchSize) == 4, "Pinned VkPhysicalDeviceLimits.maxTessellationPatchSize");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxTessellationControlPerVertexInputComponents) == 156 && sizeof(((VkPhysicalDeviceLimits *)0)->maxTessellationControlPerVertexInputComponents) == 4, "Pinned VkPhysicalDeviceLimits.maxTessellationControlPerVertexInputComponents");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxTessellationControlPerVertexOutputComponents) == 160 && sizeof(((VkPhysicalDeviceLimits *)0)->maxTessellationControlPerVertexOutputComponents) == 4, "Pinned VkPhysicalDeviceLimits.maxTessellationControlPerVertexOutputComponents");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxTessellationControlPerPatchOutputComponents) == 164 && sizeof(((VkPhysicalDeviceLimits *)0)->maxTessellationControlPerPatchOutputComponents) == 4, "Pinned VkPhysicalDeviceLimits.maxTessellationControlPerPatchOutputComponents");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxTessellationControlTotalOutputComponents) == 168 && sizeof(((VkPhysicalDeviceLimits *)0)->maxTessellationControlTotalOutputComponents) == 4, "Pinned VkPhysicalDeviceLimits.maxTessellationControlTotalOutputComponents");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxTessellationEvaluationInputComponents) == 172 && sizeof(((VkPhysicalDeviceLimits *)0)->maxTessellationEvaluationInputComponents) == 4, "Pinned VkPhysicalDeviceLimits.maxTessellationEvaluationInputComponents");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxTessellationEvaluationOutputComponents) == 176 && sizeof(((VkPhysicalDeviceLimits *)0)->maxTessellationEvaluationOutputComponents) == 4, "Pinned VkPhysicalDeviceLimits.maxTessellationEvaluationOutputComponents");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxGeometryShaderInvocations) == 180 && sizeof(((VkPhysicalDeviceLimits *)0)->maxGeometryShaderInvocations) == 4, "Pinned VkPhysicalDeviceLimits.maxGeometryShaderInvocations");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxGeometryInputComponents) == 184 && sizeof(((VkPhysicalDeviceLimits *)0)->maxGeometryInputComponents) == 4, "Pinned VkPhysicalDeviceLimits.maxGeometryInputComponents");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxGeometryOutputComponents) == 188 && sizeof(((VkPhysicalDeviceLimits *)0)->maxGeometryOutputComponents) == 4, "Pinned VkPhysicalDeviceLimits.maxGeometryOutputComponents");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxGeometryOutputVertices) == 192 && sizeof(((VkPhysicalDeviceLimits *)0)->maxGeometryOutputVertices) == 4, "Pinned VkPhysicalDeviceLimits.maxGeometryOutputVertices");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxGeometryTotalOutputComponents) == 196 && sizeof(((VkPhysicalDeviceLimits *)0)->maxGeometryTotalOutputComponents) == 4, "Pinned VkPhysicalDeviceLimits.maxGeometryTotalOutputComponents");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxFragmentInputComponents) == 200 && sizeof(((VkPhysicalDeviceLimits *)0)->maxFragmentInputComponents) == 4, "Pinned VkPhysicalDeviceLimits.maxFragmentInputComponents");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxFragmentOutputAttachments) == 204 && sizeof(((VkPhysicalDeviceLimits *)0)->maxFragmentOutputAttachments) == 4, "Pinned VkPhysicalDeviceLimits.maxFragmentOutputAttachments");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxFragmentDualSrcAttachments) == 208 && sizeof(((VkPhysicalDeviceLimits *)0)->maxFragmentDualSrcAttachments) == 4, "Pinned VkPhysicalDeviceLimits.maxFragmentDualSrcAttachments");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxFragmentCombinedOutputResources) == 212 && sizeof(((VkPhysicalDeviceLimits *)0)->maxFragmentCombinedOutputResources) == 4, "Pinned VkPhysicalDeviceLimits.maxFragmentCombinedOutputResources");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxComputeSharedMemorySize) == 216 && sizeof(((VkPhysicalDeviceLimits *)0)->maxComputeSharedMemorySize) == 4, "Pinned VkPhysicalDeviceLimits.maxComputeSharedMemorySize");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxComputeWorkGroupCount) == 220 && sizeof(((VkPhysicalDeviceLimits *)0)->maxComputeWorkGroupCount) == 12, "Pinned VkPhysicalDeviceLimits.maxComputeWorkGroupCount");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxComputeWorkGroupInvocations) == 232 && sizeof(((VkPhysicalDeviceLimits *)0)->maxComputeWorkGroupInvocations) == 4, "Pinned VkPhysicalDeviceLimits.maxComputeWorkGroupInvocations");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxComputeWorkGroupSize) == 236 && sizeof(((VkPhysicalDeviceLimits *)0)->maxComputeWorkGroupSize) == 12, "Pinned VkPhysicalDeviceLimits.maxComputeWorkGroupSize");
_Static_assert(offsetof(VkPhysicalDeviceLimits, subPixelPrecisionBits) == 248 && sizeof(((VkPhysicalDeviceLimits *)0)->subPixelPrecisionBits) == 4, "Pinned VkPhysicalDeviceLimits.subPixelPrecisionBits");
_Static_assert(offsetof(VkPhysicalDeviceLimits, subTexelPrecisionBits) == 252 && sizeof(((VkPhysicalDeviceLimits *)0)->subTexelPrecisionBits) == 4, "Pinned VkPhysicalDeviceLimits.subTexelPrecisionBits");
_Static_assert(offsetof(VkPhysicalDeviceLimits, mipmapPrecisionBits) == 256 && sizeof(((VkPhysicalDeviceLimits *)0)->mipmapPrecisionBits) == 4, "Pinned VkPhysicalDeviceLimits.mipmapPrecisionBits");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxDrawIndexedIndexValue) == 260 && sizeof(((VkPhysicalDeviceLimits *)0)->maxDrawIndexedIndexValue) == 4, "Pinned VkPhysicalDeviceLimits.maxDrawIndexedIndexValue");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxDrawIndirectCount) == 264 && sizeof(((VkPhysicalDeviceLimits *)0)->maxDrawIndirectCount) == 4, "Pinned VkPhysicalDeviceLimits.maxDrawIndirectCount");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxSamplerLodBias) == 268 && sizeof(((VkPhysicalDeviceLimits *)0)->maxSamplerLodBias) == 4, "Pinned VkPhysicalDeviceLimits.maxSamplerLodBias");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxSamplerAnisotropy) == 272 && sizeof(((VkPhysicalDeviceLimits *)0)->maxSamplerAnisotropy) == 4, "Pinned VkPhysicalDeviceLimits.maxSamplerAnisotropy");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxViewports) == 276 && sizeof(((VkPhysicalDeviceLimits *)0)->maxViewports) == 4, "Pinned VkPhysicalDeviceLimits.maxViewports");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxViewportDimensions) == 280 && sizeof(((VkPhysicalDeviceLimits *)0)->maxViewportDimensions) == 8, "Pinned VkPhysicalDeviceLimits.maxViewportDimensions");
_Static_assert(offsetof(VkPhysicalDeviceLimits, viewportBoundsRange) == 288 && sizeof(((VkPhysicalDeviceLimits *)0)->viewportBoundsRange) == 8, "Pinned VkPhysicalDeviceLimits.viewportBoundsRange");
_Static_assert(offsetof(VkPhysicalDeviceLimits, viewportSubPixelBits) == 296 && sizeof(((VkPhysicalDeviceLimits *)0)->viewportSubPixelBits) == 4, "Pinned VkPhysicalDeviceLimits.viewportSubPixelBits");
_Static_assert(offsetof(VkPhysicalDeviceLimits, minMemoryMapAlignment) == 304 && sizeof(((VkPhysicalDeviceLimits *)0)->minMemoryMapAlignment) == 8, "Pinned VkPhysicalDeviceLimits.minMemoryMapAlignment");
_Static_assert(offsetof(VkPhysicalDeviceLimits, minTexelBufferOffsetAlignment) == 312 && sizeof(((VkPhysicalDeviceLimits *)0)->minTexelBufferOffsetAlignment) == 8, "Pinned VkPhysicalDeviceLimits.minTexelBufferOffsetAlignment");
_Static_assert(offsetof(VkPhysicalDeviceLimits, minUniformBufferOffsetAlignment) == 320 && sizeof(((VkPhysicalDeviceLimits *)0)->minUniformBufferOffsetAlignment) == 8, "Pinned VkPhysicalDeviceLimits.minUniformBufferOffsetAlignment");
_Static_assert(offsetof(VkPhysicalDeviceLimits, minStorageBufferOffsetAlignment) == 328 && sizeof(((VkPhysicalDeviceLimits *)0)->minStorageBufferOffsetAlignment) == 8, "Pinned VkPhysicalDeviceLimits.minStorageBufferOffsetAlignment");
_Static_assert(offsetof(VkPhysicalDeviceLimits, minTexelOffset) == 336 && sizeof(((VkPhysicalDeviceLimits *)0)->minTexelOffset) == 4, "Pinned VkPhysicalDeviceLimits.minTexelOffset");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxTexelOffset) == 340 && sizeof(((VkPhysicalDeviceLimits *)0)->maxTexelOffset) == 4, "Pinned VkPhysicalDeviceLimits.maxTexelOffset");
_Static_assert(offsetof(VkPhysicalDeviceLimits, minTexelGatherOffset) == 344 && sizeof(((VkPhysicalDeviceLimits *)0)->minTexelGatherOffset) == 4, "Pinned VkPhysicalDeviceLimits.minTexelGatherOffset");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxTexelGatherOffset) == 348 && sizeof(((VkPhysicalDeviceLimits *)0)->maxTexelGatherOffset) == 4, "Pinned VkPhysicalDeviceLimits.maxTexelGatherOffset");
_Static_assert(offsetof(VkPhysicalDeviceLimits, minInterpolationOffset) == 352 && sizeof(((VkPhysicalDeviceLimits *)0)->minInterpolationOffset) == 4, "Pinned VkPhysicalDeviceLimits.minInterpolationOffset");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxInterpolationOffset) == 356 && sizeof(((VkPhysicalDeviceLimits *)0)->maxInterpolationOffset) == 4, "Pinned VkPhysicalDeviceLimits.maxInterpolationOffset");
_Static_assert(offsetof(VkPhysicalDeviceLimits, subPixelInterpolationOffsetBits) == 360 && sizeof(((VkPhysicalDeviceLimits *)0)->subPixelInterpolationOffsetBits) == 4, "Pinned VkPhysicalDeviceLimits.subPixelInterpolationOffsetBits");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxFramebufferWidth) == 364 && sizeof(((VkPhysicalDeviceLimits *)0)->maxFramebufferWidth) == 4, "Pinned VkPhysicalDeviceLimits.maxFramebufferWidth");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxFramebufferHeight) == 368 && sizeof(((VkPhysicalDeviceLimits *)0)->maxFramebufferHeight) == 4, "Pinned VkPhysicalDeviceLimits.maxFramebufferHeight");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxFramebufferLayers) == 372 && sizeof(((VkPhysicalDeviceLimits *)0)->maxFramebufferLayers) == 4, "Pinned VkPhysicalDeviceLimits.maxFramebufferLayers");
_Static_assert(offsetof(VkPhysicalDeviceLimits, framebufferColorSampleCounts) == 376 && sizeof(((VkPhysicalDeviceLimits *)0)->framebufferColorSampleCounts) == 4, "Pinned VkPhysicalDeviceLimits.framebufferColorSampleCounts");
_Static_assert(offsetof(VkPhysicalDeviceLimits, framebufferDepthSampleCounts) == 380 && sizeof(((VkPhysicalDeviceLimits *)0)->framebufferDepthSampleCounts) == 4, "Pinned VkPhysicalDeviceLimits.framebufferDepthSampleCounts");
_Static_assert(offsetof(VkPhysicalDeviceLimits, framebufferStencilSampleCounts) == 384 && sizeof(((VkPhysicalDeviceLimits *)0)->framebufferStencilSampleCounts) == 4, "Pinned VkPhysicalDeviceLimits.framebufferStencilSampleCounts");
_Static_assert(offsetof(VkPhysicalDeviceLimits, framebufferNoAttachmentsSampleCounts) == 388 && sizeof(((VkPhysicalDeviceLimits *)0)->framebufferNoAttachmentsSampleCounts) == 4, "Pinned VkPhysicalDeviceLimits.framebufferNoAttachmentsSampleCounts");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxColorAttachments) == 392 && sizeof(((VkPhysicalDeviceLimits *)0)->maxColorAttachments) == 4, "Pinned VkPhysicalDeviceLimits.maxColorAttachments");
_Static_assert(offsetof(VkPhysicalDeviceLimits, sampledImageColorSampleCounts) == 396 && sizeof(((VkPhysicalDeviceLimits *)0)->sampledImageColorSampleCounts) == 4, "Pinned VkPhysicalDeviceLimits.sampledImageColorSampleCounts");
_Static_assert(offsetof(VkPhysicalDeviceLimits, sampledImageIntegerSampleCounts) == 400 && sizeof(((VkPhysicalDeviceLimits *)0)->sampledImageIntegerSampleCounts) == 4, "Pinned VkPhysicalDeviceLimits.sampledImageIntegerSampleCounts");
_Static_assert(offsetof(VkPhysicalDeviceLimits, sampledImageDepthSampleCounts) == 404 && sizeof(((VkPhysicalDeviceLimits *)0)->sampledImageDepthSampleCounts) == 4, "Pinned VkPhysicalDeviceLimits.sampledImageDepthSampleCounts");
_Static_assert(offsetof(VkPhysicalDeviceLimits, sampledImageStencilSampleCounts) == 408 && sizeof(((VkPhysicalDeviceLimits *)0)->sampledImageStencilSampleCounts) == 4, "Pinned VkPhysicalDeviceLimits.sampledImageStencilSampleCounts");
_Static_assert(offsetof(VkPhysicalDeviceLimits, storageImageSampleCounts) == 412 && sizeof(((VkPhysicalDeviceLimits *)0)->storageImageSampleCounts) == 4, "Pinned VkPhysicalDeviceLimits.storageImageSampleCounts");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxSampleMaskWords) == 416 && sizeof(((VkPhysicalDeviceLimits *)0)->maxSampleMaskWords) == 4, "Pinned VkPhysicalDeviceLimits.maxSampleMaskWords");
_Static_assert(offsetof(VkPhysicalDeviceLimits, timestampComputeAndGraphics) == 420 && sizeof(((VkPhysicalDeviceLimits *)0)->timestampComputeAndGraphics) == 4, "Pinned VkPhysicalDeviceLimits.timestampComputeAndGraphics");
_Static_assert(offsetof(VkPhysicalDeviceLimits, timestampPeriod) == 424 && sizeof(((VkPhysicalDeviceLimits *)0)->timestampPeriod) == 4, "Pinned VkPhysicalDeviceLimits.timestampPeriod");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxClipDistances) == 428 && sizeof(((VkPhysicalDeviceLimits *)0)->maxClipDistances) == 4, "Pinned VkPhysicalDeviceLimits.maxClipDistances");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxCullDistances) == 432 && sizeof(((VkPhysicalDeviceLimits *)0)->maxCullDistances) == 4, "Pinned VkPhysicalDeviceLimits.maxCullDistances");
_Static_assert(offsetof(VkPhysicalDeviceLimits, maxCombinedClipAndCullDistances) == 436 && sizeof(((VkPhysicalDeviceLimits *)0)->maxCombinedClipAndCullDistances) == 4, "Pinned VkPhysicalDeviceLimits.maxCombinedClipAndCullDistances");
_Static_assert(offsetof(VkPhysicalDeviceLimits, discreteQueuePriorities) == 440 && sizeof(((VkPhysicalDeviceLimits *)0)->discreteQueuePriorities) == 4, "Pinned VkPhysicalDeviceLimits.discreteQueuePriorities");
_Static_assert(offsetof(VkPhysicalDeviceLimits, pointSizeRange) == 444 && sizeof(((VkPhysicalDeviceLimits *)0)->pointSizeRange) == 8, "Pinned VkPhysicalDeviceLimits.pointSizeRange");
_Static_assert(offsetof(VkPhysicalDeviceLimits, lineWidthRange) == 452 && sizeof(((VkPhysicalDeviceLimits *)0)->lineWidthRange) == 8, "Pinned VkPhysicalDeviceLimits.lineWidthRange");
_Static_assert(offsetof(VkPhysicalDeviceLimits, pointSizeGranularity) == 460 && sizeof(((VkPhysicalDeviceLimits *)0)->pointSizeGranularity) == 4, "Pinned VkPhysicalDeviceLimits.pointSizeGranularity");
_Static_assert(offsetof(VkPhysicalDeviceLimits, lineWidthGranularity) == 464 && sizeof(((VkPhysicalDeviceLimits *)0)->lineWidthGranularity) == 4, "Pinned VkPhysicalDeviceLimits.lineWidthGranularity");
_Static_assert(offsetof(VkPhysicalDeviceLimits, strictLines) == 468 && sizeof(((VkPhysicalDeviceLimits *)0)->strictLines) == 4, "Pinned VkPhysicalDeviceLimits.strictLines");
_Static_assert(offsetof(VkPhysicalDeviceLimits, standardSampleLocations) == 472 && sizeof(((VkPhysicalDeviceLimits *)0)->standardSampleLocations) == 4, "Pinned VkPhysicalDeviceLimits.standardSampleLocations");
_Static_assert(offsetof(VkPhysicalDeviceLimits, optimalBufferCopyOffsetAlignment) == 480 && sizeof(((VkPhysicalDeviceLimits *)0)->optimalBufferCopyOffsetAlignment) == 8, "Pinned VkPhysicalDeviceLimits.optimalBufferCopyOffsetAlignment");
_Static_assert(offsetof(VkPhysicalDeviceLimits, optimalBufferCopyRowPitchAlignment) == 488 && sizeof(((VkPhysicalDeviceLimits *)0)->optimalBufferCopyRowPitchAlignment) == 8, "Pinned VkPhysicalDeviceLimits.optimalBufferCopyRowPitchAlignment");
_Static_assert(offsetof(VkPhysicalDeviceLimits, nonCoherentAtomSize) == 496 && sizeof(((VkPhysicalDeviceLimits *)0)->nonCoherentAtomSize) == 8, "Pinned VkPhysicalDeviceLimits.nonCoherentAtomSize");
_Static_assert(sizeof(VkPhysicalDeviceSparseProperties) == 20 && _Alignof(VkPhysicalDeviceSparseProperties) == 4, "Pinned VkPhysicalDeviceSparseProperties ABI");
_Static_assert(offsetof(VkPhysicalDeviceSparseProperties, residencyStandard2DBlockShape) == 0 && sizeof(((VkPhysicalDeviceSparseProperties *)0)->residencyStandard2DBlockShape) == 4, "Pinned VkPhysicalDeviceSparseProperties.residencyStandard2DBlockShape");
_Static_assert(offsetof(VkPhysicalDeviceSparseProperties, residencyStandard2DMultisampleBlockShape) == 4 && sizeof(((VkPhysicalDeviceSparseProperties *)0)->residencyStandard2DMultisampleBlockShape) == 4, "Pinned VkPhysicalDeviceSparseProperties.residencyStandard2DMultisampleBlockShape");
_Static_assert(offsetof(VkPhysicalDeviceSparseProperties, residencyStandard3DBlockShape) == 8 && sizeof(((VkPhysicalDeviceSparseProperties *)0)->residencyStandard3DBlockShape) == 4, "Pinned VkPhysicalDeviceSparseProperties.residencyStandard3DBlockShape");
_Static_assert(offsetof(VkPhysicalDeviceSparseProperties, residencyAlignedMipSize) == 12 && sizeof(((VkPhysicalDeviceSparseProperties *)0)->residencyAlignedMipSize) == 4, "Pinned VkPhysicalDeviceSparseProperties.residencyAlignedMipSize");
_Static_assert(offsetof(VkPhysicalDeviceSparseProperties, residencyNonResidentStrict) == 16 && sizeof(((VkPhysicalDeviceSparseProperties *)0)->residencyNonResidentStrict) == 4, "Pinned VkPhysicalDeviceSparseProperties.residencyNonResidentStrict");
_Static_assert(sizeof(VkConformanceVersion) == 4 && _Alignof(VkConformanceVersion) == 1, "Pinned VkConformanceVersion ABI");
_Static_assert(offsetof(VkConformanceVersion, major) == 0 && sizeof(((VkConformanceVersion *)0)->major) == 1, "Pinned VkConformanceVersion.major");
_Static_assert(offsetof(VkConformanceVersion, minor) == 1 && sizeof(((VkConformanceVersion *)0)->minor) == 1, "Pinned VkConformanceVersion.minor");
_Static_assert(offsetof(VkConformanceVersion, subminor) == 2 && sizeof(((VkConformanceVersion *)0)->subminor) == 1, "Pinned VkConformanceVersion.subminor");
_Static_assert(offsetof(VkConformanceVersion, patch) == 3 && sizeof(((VkConformanceVersion *)0)->patch) == 1, "Pinned VkConformanceVersion.patch");
_Static_assert(sizeof(VkPhysicalDeviceVulkan11Properties) == 112 && _Alignof(VkPhysicalDeviceVulkan11Properties) == 8, "Pinned VkPhysicalDeviceVulkan11Properties ABI");
_Static_assert(offsetof(VkPhysicalDeviceVulkan11Properties, sType) == 0 && sizeof(((VkPhysicalDeviceVulkan11Properties *)0)->sType) == 4, "Pinned VkPhysicalDeviceVulkan11Properties.sType");
_Static_assert(offsetof(VkPhysicalDeviceVulkan11Properties, pNext) == 8 && sizeof(((VkPhysicalDeviceVulkan11Properties *)0)->pNext) == 8, "Pinned VkPhysicalDeviceVulkan11Properties.pNext");
_Static_assert(offsetof(VkPhysicalDeviceVulkan11Properties, deviceUUID) == 16 && sizeof(((VkPhysicalDeviceVulkan11Properties *)0)->deviceUUID) == 16, "Pinned VkPhysicalDeviceVulkan11Properties.deviceUUID");
_Static_assert(offsetof(VkPhysicalDeviceVulkan11Properties, driverUUID) == 32 && sizeof(((VkPhysicalDeviceVulkan11Properties *)0)->driverUUID) == 16, "Pinned VkPhysicalDeviceVulkan11Properties.driverUUID");
_Static_assert(offsetof(VkPhysicalDeviceVulkan11Properties, deviceLUID) == 48 && sizeof(((VkPhysicalDeviceVulkan11Properties *)0)->deviceLUID) == 8, "Pinned VkPhysicalDeviceVulkan11Properties.deviceLUID");
_Static_assert(offsetof(VkPhysicalDeviceVulkan11Properties, deviceNodeMask) == 56 && sizeof(((VkPhysicalDeviceVulkan11Properties *)0)->deviceNodeMask) == 4, "Pinned VkPhysicalDeviceVulkan11Properties.deviceNodeMask");
_Static_assert(offsetof(VkPhysicalDeviceVulkan11Properties, deviceLUIDValid) == 60 && sizeof(((VkPhysicalDeviceVulkan11Properties *)0)->deviceLUIDValid) == 4, "Pinned VkPhysicalDeviceVulkan11Properties.deviceLUIDValid");
_Static_assert(offsetof(VkPhysicalDeviceVulkan11Properties, subgroupSize) == 64 && sizeof(((VkPhysicalDeviceVulkan11Properties *)0)->subgroupSize) == 4, "Pinned VkPhysicalDeviceVulkan11Properties.subgroupSize");
_Static_assert(offsetof(VkPhysicalDeviceVulkan11Properties, subgroupSupportedStages) == 68 && sizeof(((VkPhysicalDeviceVulkan11Properties *)0)->subgroupSupportedStages) == 4, "Pinned VkPhysicalDeviceVulkan11Properties.subgroupSupportedStages");
_Static_assert(offsetof(VkPhysicalDeviceVulkan11Properties, subgroupSupportedOperations) == 72 && sizeof(((VkPhysicalDeviceVulkan11Properties *)0)->subgroupSupportedOperations) == 4, "Pinned VkPhysicalDeviceVulkan11Properties.subgroupSupportedOperations");
_Static_assert(offsetof(VkPhysicalDeviceVulkan11Properties, subgroupQuadOperationsInAllStages) == 76 && sizeof(((VkPhysicalDeviceVulkan11Properties *)0)->subgroupQuadOperationsInAllStages) == 4, "Pinned VkPhysicalDeviceVulkan11Properties.subgroupQuadOperationsInAllStages");
_Static_assert(offsetof(VkPhysicalDeviceVulkan11Properties, pointClippingBehavior) == 80 && sizeof(((VkPhysicalDeviceVulkan11Properties *)0)->pointClippingBehavior) == 4, "Pinned VkPhysicalDeviceVulkan11Properties.pointClippingBehavior");
_Static_assert(offsetof(VkPhysicalDeviceVulkan11Properties, maxMultiviewViewCount) == 84 && sizeof(((VkPhysicalDeviceVulkan11Properties *)0)->maxMultiviewViewCount) == 4, "Pinned VkPhysicalDeviceVulkan11Properties.maxMultiviewViewCount");
_Static_assert(offsetof(VkPhysicalDeviceVulkan11Properties, maxMultiviewInstanceIndex) == 88 && sizeof(((VkPhysicalDeviceVulkan11Properties *)0)->maxMultiviewInstanceIndex) == 4, "Pinned VkPhysicalDeviceVulkan11Properties.maxMultiviewInstanceIndex");
_Static_assert(offsetof(VkPhysicalDeviceVulkan11Properties, protectedNoFault) == 92 && sizeof(((VkPhysicalDeviceVulkan11Properties *)0)->protectedNoFault) == 4, "Pinned VkPhysicalDeviceVulkan11Properties.protectedNoFault");
_Static_assert(offsetof(VkPhysicalDeviceVulkan11Properties, maxPerSetDescriptors) == 96 && sizeof(((VkPhysicalDeviceVulkan11Properties *)0)->maxPerSetDescriptors) == 4, "Pinned VkPhysicalDeviceVulkan11Properties.maxPerSetDescriptors");
_Static_assert(offsetof(VkPhysicalDeviceVulkan11Properties, maxMemoryAllocationSize) == 104 && sizeof(((VkPhysicalDeviceVulkan11Properties *)0)->maxMemoryAllocationSize) == 8, "Pinned VkPhysicalDeviceVulkan11Properties.maxMemoryAllocationSize");
_Static_assert(sizeof(VkPhysicalDeviceVulkan12Properties) == 736 && _Alignof(VkPhysicalDeviceVulkan12Properties) == 8, "Pinned VkPhysicalDeviceVulkan12Properties ABI");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, sType) == 0 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->sType) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.sType");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, pNext) == 8 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->pNext) == 8, "Pinned VkPhysicalDeviceVulkan12Properties.pNext");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, driverID) == 16 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->driverID) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.driverID");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, driverName) == 20 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->driverName) == 256, "Pinned VkPhysicalDeviceVulkan12Properties.driverName");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, driverInfo) == 276 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->driverInfo) == 256, "Pinned VkPhysicalDeviceVulkan12Properties.driverInfo");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, conformanceVersion) == 532 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->conformanceVersion) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.conformanceVersion");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, denormBehaviorIndependence) == 536 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->denormBehaviorIndependence) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.denormBehaviorIndependence");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, roundingModeIndependence) == 540 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->roundingModeIndependence) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.roundingModeIndependence");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, shaderSignedZeroInfNanPreserveFloat16) == 544 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->shaderSignedZeroInfNanPreserveFloat16) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.shaderSignedZeroInfNanPreserveFloat16");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, shaderSignedZeroInfNanPreserveFloat32) == 548 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->shaderSignedZeroInfNanPreserveFloat32) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.shaderSignedZeroInfNanPreserveFloat32");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, shaderSignedZeroInfNanPreserveFloat64) == 552 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->shaderSignedZeroInfNanPreserveFloat64) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.shaderSignedZeroInfNanPreserveFloat64");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, shaderDenormPreserveFloat16) == 556 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->shaderDenormPreserveFloat16) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.shaderDenormPreserveFloat16");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, shaderDenormPreserveFloat32) == 560 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->shaderDenormPreserveFloat32) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.shaderDenormPreserveFloat32");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, shaderDenormPreserveFloat64) == 564 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->shaderDenormPreserveFloat64) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.shaderDenormPreserveFloat64");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, shaderDenormFlushToZeroFloat16) == 568 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->shaderDenormFlushToZeroFloat16) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.shaderDenormFlushToZeroFloat16");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, shaderDenormFlushToZeroFloat32) == 572 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->shaderDenormFlushToZeroFloat32) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.shaderDenormFlushToZeroFloat32");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, shaderDenormFlushToZeroFloat64) == 576 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->shaderDenormFlushToZeroFloat64) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.shaderDenormFlushToZeroFloat64");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, shaderRoundingModeRTEFloat16) == 580 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->shaderRoundingModeRTEFloat16) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.shaderRoundingModeRTEFloat16");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, shaderRoundingModeRTEFloat32) == 584 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->shaderRoundingModeRTEFloat32) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.shaderRoundingModeRTEFloat32");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, shaderRoundingModeRTEFloat64) == 588 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->shaderRoundingModeRTEFloat64) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.shaderRoundingModeRTEFloat64");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, shaderRoundingModeRTZFloat16) == 592 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->shaderRoundingModeRTZFloat16) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.shaderRoundingModeRTZFloat16");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, shaderRoundingModeRTZFloat32) == 596 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->shaderRoundingModeRTZFloat32) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.shaderRoundingModeRTZFloat32");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, shaderRoundingModeRTZFloat64) == 600 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->shaderRoundingModeRTZFloat64) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.shaderRoundingModeRTZFloat64");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, maxUpdateAfterBindDescriptorsInAllPools) == 604 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->maxUpdateAfterBindDescriptorsInAllPools) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.maxUpdateAfterBindDescriptorsInAllPools");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, shaderUniformBufferArrayNonUniformIndexingNative) == 608 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->shaderUniformBufferArrayNonUniformIndexingNative) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.shaderUniformBufferArrayNonUniformIndexingNative");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, shaderSampledImageArrayNonUniformIndexingNative) == 612 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->shaderSampledImageArrayNonUniformIndexingNative) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.shaderSampledImageArrayNonUniformIndexingNative");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, shaderStorageBufferArrayNonUniformIndexingNative) == 616 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->shaderStorageBufferArrayNonUniformIndexingNative) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.shaderStorageBufferArrayNonUniformIndexingNative");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, shaderStorageImageArrayNonUniformIndexingNative) == 620 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->shaderStorageImageArrayNonUniformIndexingNative) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.shaderStorageImageArrayNonUniformIndexingNative");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, shaderInputAttachmentArrayNonUniformIndexingNative) == 624 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->shaderInputAttachmentArrayNonUniformIndexingNative) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.shaderInputAttachmentArrayNonUniformIndexingNative");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, robustBufferAccessUpdateAfterBind) == 628 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->robustBufferAccessUpdateAfterBind) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.robustBufferAccessUpdateAfterBind");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, quadDivergentImplicitLod) == 632 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->quadDivergentImplicitLod) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.quadDivergentImplicitLod");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, maxPerStageDescriptorUpdateAfterBindSamplers) == 636 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->maxPerStageDescriptorUpdateAfterBindSamplers) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.maxPerStageDescriptorUpdateAfterBindSamplers");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, maxPerStageDescriptorUpdateAfterBindUniformBuffers) == 640 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->maxPerStageDescriptorUpdateAfterBindUniformBuffers) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.maxPerStageDescriptorUpdateAfterBindUniformBuffers");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, maxPerStageDescriptorUpdateAfterBindStorageBuffers) == 644 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->maxPerStageDescriptorUpdateAfterBindStorageBuffers) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.maxPerStageDescriptorUpdateAfterBindStorageBuffers");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, maxPerStageDescriptorUpdateAfterBindSampledImages) == 648 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->maxPerStageDescriptorUpdateAfterBindSampledImages) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.maxPerStageDescriptorUpdateAfterBindSampledImages");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, maxPerStageDescriptorUpdateAfterBindStorageImages) == 652 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->maxPerStageDescriptorUpdateAfterBindStorageImages) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.maxPerStageDescriptorUpdateAfterBindStorageImages");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, maxPerStageDescriptorUpdateAfterBindInputAttachments) == 656 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->maxPerStageDescriptorUpdateAfterBindInputAttachments) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.maxPerStageDescriptorUpdateAfterBindInputAttachments");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, maxPerStageUpdateAfterBindResources) == 660 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->maxPerStageUpdateAfterBindResources) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.maxPerStageUpdateAfterBindResources");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, maxDescriptorSetUpdateAfterBindSamplers) == 664 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->maxDescriptorSetUpdateAfterBindSamplers) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.maxDescriptorSetUpdateAfterBindSamplers");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, maxDescriptorSetUpdateAfterBindUniformBuffers) == 668 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->maxDescriptorSetUpdateAfterBindUniformBuffers) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.maxDescriptorSetUpdateAfterBindUniformBuffers");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, maxDescriptorSetUpdateAfterBindUniformBuffersDynamic) == 672 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->maxDescriptorSetUpdateAfterBindUniformBuffersDynamic) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.maxDescriptorSetUpdateAfterBindUniformBuffersDynamic");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, maxDescriptorSetUpdateAfterBindStorageBuffers) == 676 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->maxDescriptorSetUpdateAfterBindStorageBuffers) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.maxDescriptorSetUpdateAfterBindStorageBuffers");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, maxDescriptorSetUpdateAfterBindStorageBuffersDynamic) == 680 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->maxDescriptorSetUpdateAfterBindStorageBuffersDynamic) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.maxDescriptorSetUpdateAfterBindStorageBuffersDynamic");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, maxDescriptorSetUpdateAfterBindSampledImages) == 684 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->maxDescriptorSetUpdateAfterBindSampledImages) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.maxDescriptorSetUpdateAfterBindSampledImages");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, maxDescriptorSetUpdateAfterBindStorageImages) == 688 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->maxDescriptorSetUpdateAfterBindStorageImages) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.maxDescriptorSetUpdateAfterBindStorageImages");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, maxDescriptorSetUpdateAfterBindInputAttachments) == 692 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->maxDescriptorSetUpdateAfterBindInputAttachments) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.maxDescriptorSetUpdateAfterBindInputAttachments");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, supportedDepthResolveModes) == 696 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->supportedDepthResolveModes) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.supportedDepthResolveModes");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, supportedStencilResolveModes) == 700 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->supportedStencilResolveModes) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.supportedStencilResolveModes");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, independentResolveNone) == 704 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->independentResolveNone) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.independentResolveNone");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, independentResolve) == 708 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->independentResolve) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.independentResolve");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, filterMinmaxSingleComponentFormats) == 712 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->filterMinmaxSingleComponentFormats) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.filterMinmaxSingleComponentFormats");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, filterMinmaxImageComponentMapping) == 716 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->filterMinmaxImageComponentMapping) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.filterMinmaxImageComponentMapping");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, maxTimelineSemaphoreValueDifference) == 720 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->maxTimelineSemaphoreValueDifference) == 8, "Pinned VkPhysicalDeviceVulkan12Properties.maxTimelineSemaphoreValueDifference");
_Static_assert(offsetof(VkPhysicalDeviceVulkan12Properties, framebufferIntegerColorSampleCounts) == 728 && sizeof(((VkPhysicalDeviceVulkan12Properties *)0)->framebufferIntegerColorSampleCounts) == 4, "Pinned VkPhysicalDeviceVulkan12Properties.framebufferIntegerColorSampleCounts");
_Static_assert(sizeof(VkPhysicalDeviceVulkan13Properties) == 216 && _Alignof(VkPhysicalDeviceVulkan13Properties) == 8, "Pinned VkPhysicalDeviceVulkan13Properties ABI");
_Static_assert(offsetof(VkPhysicalDeviceVulkan13Properties, sType) == 0 && sizeof(((VkPhysicalDeviceVulkan13Properties *)0)->sType) == 4, "Pinned VkPhysicalDeviceVulkan13Properties.sType");
_Static_assert(offsetof(VkPhysicalDeviceVulkan13Properties, pNext) == 8 && sizeof(((VkPhysicalDeviceVulkan13Properties *)0)->pNext) == 8, "Pinned VkPhysicalDeviceVulkan13Properties.pNext");
_Static_assert(offsetof(VkPhysicalDeviceVulkan13Properties, minSubgroupSize) == 16 && sizeof(((VkPhysicalDeviceVulkan13Properties *)0)->minSubgroupSize) == 4, "Pinned VkPhysicalDeviceVulkan13Properties.minSubgroupSize");
_Static_assert(offsetof(VkPhysicalDeviceVulkan13Properties, maxSubgroupSize) == 20 && sizeof(((VkPhysicalDeviceVulkan13Properties *)0)->maxSubgroupSize) == 4, "Pinned VkPhysicalDeviceVulkan13Properties.maxSubgroupSize");
_Static_assert(offsetof(VkPhysicalDeviceVulkan13Properties, maxComputeWorkgroupSubgroups) == 24 && sizeof(((VkPhysicalDeviceVulkan13Properties *)0)->maxComputeWorkgroupSubgroups) == 4, "Pinned VkPhysicalDeviceVulkan13Properties.maxComputeWorkgroupSubgroups");
_Static_assert(offsetof(VkPhysicalDeviceVulkan13Properties, requiredSubgroupSizeStages) == 28 && sizeof(((VkPhysicalDeviceVulkan13Properties *)0)->requiredSubgroupSizeStages) == 4, "Pinned VkPhysicalDeviceVulkan13Properties.requiredSubgroupSizeStages");
_Static_assert(offsetof(VkPhysicalDeviceVulkan13Properties, maxInlineUniformBlockSize) == 32 && sizeof(((VkPhysicalDeviceVulkan13Properties *)0)->maxInlineUniformBlockSize) == 4, "Pinned VkPhysicalDeviceVulkan13Properties.maxInlineUniformBlockSize");
_Static_assert(offsetof(VkPhysicalDeviceVulkan13Properties, maxPerStageDescriptorInlineUniformBlocks) == 36 && sizeof(((VkPhysicalDeviceVulkan13Properties *)0)->maxPerStageDescriptorInlineUniformBlocks) == 4, "Pinned VkPhysicalDeviceVulkan13Properties.maxPerStageDescriptorInlineUniformBlocks");
_Static_assert(offsetof(VkPhysicalDeviceVulkan13Properties, maxPerStageDescriptorUpdateAfterBindInlineUniformBlocks) == 40 && sizeof(((VkPhysicalDeviceVulkan13Properties *)0)->maxPerStageDescriptorUpdateAfterBindInlineUniformBlocks) == 4, "Pinned VkPhysicalDeviceVulkan13Properties.maxPerStageDescriptorUpdateAfterBindInlineUniformBlocks");
_Static_assert(offsetof(VkPhysicalDeviceVulkan13Properties, maxDescriptorSetInlineUniformBlocks) == 44 && sizeof(((VkPhysicalDeviceVulkan13Properties *)0)->maxDescriptorSetInlineUniformBlocks) == 4, "Pinned VkPhysicalDeviceVulkan13Properties.maxDescriptorSetInlineUniformBlocks");
_Static_assert(offsetof(VkPhysicalDeviceVulkan13Properties, maxDescriptorSetUpdateAfterBindInlineUniformBlocks) == 48 && sizeof(((VkPhysicalDeviceVulkan13Properties *)0)->maxDescriptorSetUpdateAfterBindInlineUniformBlocks) == 4, "Pinned VkPhysicalDeviceVulkan13Properties.maxDescriptorSetUpdateAfterBindInlineUniformBlocks");
_Static_assert(offsetof(VkPhysicalDeviceVulkan13Properties, maxInlineUniformTotalSize) == 52 && sizeof(((VkPhysicalDeviceVulkan13Properties *)0)->maxInlineUniformTotalSize) == 4, "Pinned VkPhysicalDeviceVulkan13Properties.maxInlineUniformTotalSize");
_Static_assert(offsetof(VkPhysicalDeviceVulkan13Properties, integerDotProduct8BitUnsignedAccelerated) == 56 && sizeof(((VkPhysicalDeviceVulkan13Properties *)0)->integerDotProduct8BitUnsignedAccelerated) == 4, "Pinned VkPhysicalDeviceVulkan13Properties.integerDotProduct8BitUnsignedAccelerated");
_Static_assert(offsetof(VkPhysicalDeviceVulkan13Properties, integerDotProduct8BitSignedAccelerated) == 60 && sizeof(((VkPhysicalDeviceVulkan13Properties *)0)->integerDotProduct8BitSignedAccelerated) == 4, "Pinned VkPhysicalDeviceVulkan13Properties.integerDotProduct8BitSignedAccelerated");
_Static_assert(offsetof(VkPhysicalDeviceVulkan13Properties, integerDotProduct8BitMixedSignednessAccelerated) == 64 && sizeof(((VkPhysicalDeviceVulkan13Properties *)0)->integerDotProduct8BitMixedSignednessAccelerated) == 4, "Pinned VkPhysicalDeviceVulkan13Properties.integerDotProduct8BitMixedSignednessAccelerated");
_Static_assert(offsetof(VkPhysicalDeviceVulkan13Properties, integerDotProduct4x8BitPackedUnsignedAccelerated) == 68 && sizeof(((VkPhysicalDeviceVulkan13Properties *)0)->integerDotProduct4x8BitPackedUnsignedAccelerated) == 4, "Pinned VkPhysicalDeviceVulkan13Properties.integerDotProduct4x8BitPackedUnsignedAccelerated");
_Static_assert(offsetof(VkPhysicalDeviceVulkan13Properties, integerDotProduct4x8BitPackedSignedAccelerated) == 72 && sizeof(((VkPhysicalDeviceVulkan13Properties *)0)->integerDotProduct4x8BitPackedSignedAccelerated) == 4, "Pinned VkPhysicalDeviceVulkan13Properties.integerDotProduct4x8BitPackedSignedAccelerated");
_Static_assert(offsetof(VkPhysicalDeviceVulkan13Properties, integerDotProduct4x8BitPackedMixedSignednessAccelerated) == 76 && sizeof(((VkPhysicalDeviceVulkan13Properties *)0)->integerDotProduct4x8BitPackedMixedSignednessAccelerated) == 4, "Pinned VkPhysicalDeviceVulkan13Properties.integerDotProduct4x8BitPackedMixedSignednessAccelerated");
_Static_assert(offsetof(VkPhysicalDeviceVulkan13Properties, integerDotProduct16BitUnsignedAccelerated) == 80 && sizeof(((VkPhysicalDeviceVulkan13Properties *)0)->integerDotProduct16BitUnsignedAccelerated) == 4, "Pinned VkPhysicalDeviceVulkan13Properties.integerDotProduct16BitUnsignedAccelerated");
_Static_assert(offsetof(VkPhysicalDeviceVulkan13Properties, integerDotProduct16BitSignedAccelerated) == 84 && sizeof(((VkPhysicalDeviceVulkan13Properties *)0)->integerDotProduct16BitSignedAccelerated) == 4, "Pinned VkPhysicalDeviceVulkan13Properties.integerDotProduct16BitSignedAccelerated");
_Static_assert(offsetof(VkPhysicalDeviceVulkan13Properties, integerDotProduct16BitMixedSignednessAccelerated) == 88 && sizeof(((VkPhysicalDeviceVulkan13Properties *)0)->integerDotProduct16BitMixedSignednessAccelerated) == 4, "Pinned VkPhysicalDeviceVulkan13Properties.integerDotProduct16BitMixedSignednessAccelerated");
_Static_assert(offsetof(VkPhysicalDeviceVulkan13Properties, integerDotProduct32BitUnsignedAccelerated) == 92 && sizeof(((VkPhysicalDeviceVulkan13Properties *)0)->integerDotProduct32BitUnsignedAccelerated) == 4, "Pinned VkPhysicalDeviceVulkan13Properties.integerDotProduct32BitUnsignedAccelerated");
_Static_assert(offsetof(VkPhysicalDeviceVulkan13Properties, integerDotProduct32BitSignedAccelerated) == 96 && sizeof(((VkPhysicalDeviceVulkan13Properties *)0)->integerDotProduct32BitSignedAccelerated) == 4, "Pinned VkPhysicalDeviceVulkan13Properties.integerDotProduct32BitSignedAccelerated");
_Static_assert(offsetof(VkPhysicalDeviceVulkan13Properties, integerDotProduct32BitMixedSignednessAccelerated) == 100 && sizeof(((VkPhysicalDeviceVulkan13Properties *)0)->integerDotProduct32BitMixedSignednessAccelerated) == 4, "Pinned VkPhysicalDeviceVulkan13Properties.integerDotProduct32BitMixedSignednessAccelerated");
_Static_assert(offsetof(VkPhysicalDeviceVulkan13Properties, integerDotProduct64BitUnsignedAccelerated) == 104 && sizeof(((VkPhysicalDeviceVulkan13Properties *)0)->integerDotProduct64BitUnsignedAccelerated) == 4, "Pinned VkPhysicalDeviceVulkan13Properties.integerDotProduct64BitUnsignedAccelerated");
_Static_assert(offsetof(VkPhysicalDeviceVulkan13Properties, integerDotProduct64BitSignedAccelerated) == 108 && sizeof(((VkPhysicalDeviceVulkan13Properties *)0)->integerDotProduct64BitSignedAccelerated) == 4, "Pinned VkPhysicalDeviceVulkan13Properties.integerDotProduct64BitSignedAccelerated");
_Static_assert(offsetof(VkPhysicalDeviceVulkan13Properties, integerDotProduct64BitMixedSignednessAccelerated) == 112 && sizeof(((VkPhysicalDeviceVulkan13Properties *)0)->integerDotProduct64BitMixedSignednessAccelerated) == 4, "Pinned VkPhysicalDeviceVulkan13Properties.integerDotProduct64BitMixedSignednessAccelerated");
_Static_assert(offsetof(VkPhysicalDeviceVulkan13Properties, integerDotProductAccumulatingSaturating8BitUnsignedAccelerated) == 116 && sizeof(((VkPhysicalDeviceVulkan13Properties *)0)->integerDotProductAccumulatingSaturating8BitUnsignedAccelerated) == 4, "Pinned VkPhysicalDeviceVulkan13Properties.integerDotProductAccumulatingSaturating8BitUnsignedAccelerated");
_Static_assert(offsetof(VkPhysicalDeviceVulkan13Properties, integerDotProductAccumulatingSaturating8BitSignedAccelerated) == 120 && sizeof(((VkPhysicalDeviceVulkan13Properties *)0)->integerDotProductAccumulatingSaturating8BitSignedAccelerated) == 4, "Pinned VkPhysicalDeviceVulkan13Properties.integerDotProductAccumulatingSaturating8BitSignedAccelerated");
_Static_assert(offsetof(VkPhysicalDeviceVulkan13Properties, integerDotProductAccumulatingSaturating8BitMixedSignednessAccelerated) == 124 && sizeof(((VkPhysicalDeviceVulkan13Properties *)0)->integerDotProductAccumulatingSaturating8BitMixedSignednessAccelerated) == 4, "Pinned VkPhysicalDeviceVulkan13Properties.integerDotProductAccumulatingSaturating8BitMixedSignednessAccelerated");
_Static_assert(offsetof(VkPhysicalDeviceVulkan13Properties, integerDotProductAccumulatingSaturating4x8BitPackedUnsignedAccelerated) == 128 && sizeof(((VkPhysicalDeviceVulkan13Properties *)0)->integerDotProductAccumulatingSaturating4x8BitPackedUnsignedAccelerated) == 4, "Pinned VkPhysicalDeviceVulkan13Properties.integerDotProductAccumulatingSaturating4x8BitPackedUnsignedAccelerated");
_Static_assert(offsetof(VkPhysicalDeviceVulkan13Properties, integerDotProductAccumulatingSaturating4x8BitPackedSignedAccelerated) == 132 && sizeof(((VkPhysicalDeviceVulkan13Properties *)0)->integerDotProductAccumulatingSaturating4x8BitPackedSignedAccelerated) == 4, "Pinned VkPhysicalDeviceVulkan13Properties.integerDotProductAccumulatingSaturating4x8BitPackedSignedAccelerated");
_Static_assert(offsetof(VkPhysicalDeviceVulkan13Properties, integerDotProductAccumulatingSaturating4x8BitPackedMixedSignednessAccelerated) == 136 && sizeof(((VkPhysicalDeviceVulkan13Properties *)0)->integerDotProductAccumulatingSaturating4x8BitPackedMixedSignednessAccelerated) == 4, "Pinned VkPhysicalDeviceVulkan13Properties.integerDotProductAccumulatingSaturating4x8BitPackedMixedSignednessAccelerated");
_Static_assert(offsetof(VkPhysicalDeviceVulkan13Properties, integerDotProductAccumulatingSaturating16BitUnsignedAccelerated) == 140 && sizeof(((VkPhysicalDeviceVulkan13Properties *)0)->integerDotProductAccumulatingSaturating16BitUnsignedAccelerated) == 4, "Pinned VkPhysicalDeviceVulkan13Properties.integerDotProductAccumulatingSaturating16BitUnsignedAccelerated");
_Static_assert(offsetof(VkPhysicalDeviceVulkan13Properties, integerDotProductAccumulatingSaturating16BitSignedAccelerated) == 144 && sizeof(((VkPhysicalDeviceVulkan13Properties *)0)->integerDotProductAccumulatingSaturating16BitSignedAccelerated) == 4, "Pinned VkPhysicalDeviceVulkan13Properties.integerDotProductAccumulatingSaturating16BitSignedAccelerated");
_Static_assert(offsetof(VkPhysicalDeviceVulkan13Properties, integerDotProductAccumulatingSaturating16BitMixedSignednessAccelerated) == 148 && sizeof(((VkPhysicalDeviceVulkan13Properties *)0)->integerDotProductAccumulatingSaturating16BitMixedSignednessAccelerated) == 4, "Pinned VkPhysicalDeviceVulkan13Properties.integerDotProductAccumulatingSaturating16BitMixedSignednessAccelerated");
_Static_assert(offsetof(VkPhysicalDeviceVulkan13Properties, integerDotProductAccumulatingSaturating32BitUnsignedAccelerated) == 152 && sizeof(((VkPhysicalDeviceVulkan13Properties *)0)->integerDotProductAccumulatingSaturating32BitUnsignedAccelerated) == 4, "Pinned VkPhysicalDeviceVulkan13Properties.integerDotProductAccumulatingSaturating32BitUnsignedAccelerated");
_Static_assert(offsetof(VkPhysicalDeviceVulkan13Properties, integerDotProductAccumulatingSaturating32BitSignedAccelerated) == 156 && sizeof(((VkPhysicalDeviceVulkan13Properties *)0)->integerDotProductAccumulatingSaturating32BitSignedAccelerated) == 4, "Pinned VkPhysicalDeviceVulkan13Properties.integerDotProductAccumulatingSaturating32BitSignedAccelerated");
_Static_assert(offsetof(VkPhysicalDeviceVulkan13Properties, integerDotProductAccumulatingSaturating32BitMixedSignednessAccelerated) == 160 && sizeof(((VkPhysicalDeviceVulkan13Properties *)0)->integerDotProductAccumulatingSaturating32BitMixedSignednessAccelerated) == 4, "Pinned VkPhysicalDeviceVulkan13Properties.integerDotProductAccumulatingSaturating32BitMixedSignednessAccelerated");
_Static_assert(offsetof(VkPhysicalDeviceVulkan13Properties, integerDotProductAccumulatingSaturating64BitUnsignedAccelerated) == 164 && sizeof(((VkPhysicalDeviceVulkan13Properties *)0)->integerDotProductAccumulatingSaturating64BitUnsignedAccelerated) == 4, "Pinned VkPhysicalDeviceVulkan13Properties.integerDotProductAccumulatingSaturating64BitUnsignedAccelerated");
_Static_assert(offsetof(VkPhysicalDeviceVulkan13Properties, integerDotProductAccumulatingSaturating64BitSignedAccelerated) == 168 && sizeof(((VkPhysicalDeviceVulkan13Properties *)0)->integerDotProductAccumulatingSaturating64BitSignedAccelerated) == 4, "Pinned VkPhysicalDeviceVulkan13Properties.integerDotProductAccumulatingSaturating64BitSignedAccelerated");
_Static_assert(offsetof(VkPhysicalDeviceVulkan13Properties, integerDotProductAccumulatingSaturating64BitMixedSignednessAccelerated) == 172 && sizeof(((VkPhysicalDeviceVulkan13Properties *)0)->integerDotProductAccumulatingSaturating64BitMixedSignednessAccelerated) == 4, "Pinned VkPhysicalDeviceVulkan13Properties.integerDotProductAccumulatingSaturating64BitMixedSignednessAccelerated");
_Static_assert(offsetof(VkPhysicalDeviceVulkan13Properties, storageTexelBufferOffsetAlignmentBytes) == 176 && sizeof(((VkPhysicalDeviceVulkan13Properties *)0)->storageTexelBufferOffsetAlignmentBytes) == 8, "Pinned VkPhysicalDeviceVulkan13Properties.storageTexelBufferOffsetAlignmentBytes");
_Static_assert(offsetof(VkPhysicalDeviceVulkan13Properties, storageTexelBufferOffsetSingleTexelAlignment) == 184 && sizeof(((VkPhysicalDeviceVulkan13Properties *)0)->storageTexelBufferOffsetSingleTexelAlignment) == 4, "Pinned VkPhysicalDeviceVulkan13Properties.storageTexelBufferOffsetSingleTexelAlignment");
_Static_assert(offsetof(VkPhysicalDeviceVulkan13Properties, uniformTexelBufferOffsetAlignmentBytes) == 192 && sizeof(((VkPhysicalDeviceVulkan13Properties *)0)->uniformTexelBufferOffsetAlignmentBytes) == 8, "Pinned VkPhysicalDeviceVulkan13Properties.uniformTexelBufferOffsetAlignmentBytes");
_Static_assert(offsetof(VkPhysicalDeviceVulkan13Properties, uniformTexelBufferOffsetSingleTexelAlignment) == 200 && sizeof(((VkPhysicalDeviceVulkan13Properties *)0)->uniformTexelBufferOffsetSingleTexelAlignment) == 4, "Pinned VkPhysicalDeviceVulkan13Properties.uniformTexelBufferOffsetSingleTexelAlignment");
_Static_assert(offsetof(VkPhysicalDeviceVulkan13Properties, maxBufferSize) == 208 && sizeof(((VkPhysicalDeviceVulkan13Properties *)0)->maxBufferSize) == 8, "Pinned VkPhysicalDeviceVulkan13Properties.maxBufferSize");
_Static_assert(sizeof(VkPhysicalDeviceRobustness2PropertiesEXT) == 32 && _Alignof(VkPhysicalDeviceRobustness2PropertiesEXT) == 8, "Pinned VkPhysicalDeviceRobustness2PropertiesEXT ABI");
_Static_assert(offsetof(VkPhysicalDeviceRobustness2PropertiesEXT, sType) == 0 && sizeof(((VkPhysicalDeviceRobustness2PropertiesEXT *)0)->sType) == 4, "Pinned VkPhysicalDeviceRobustness2PropertiesEXT.sType");
_Static_assert(offsetof(VkPhysicalDeviceRobustness2PropertiesEXT, pNext) == 8 && sizeof(((VkPhysicalDeviceRobustness2PropertiesEXT *)0)->pNext) == 8, "Pinned VkPhysicalDeviceRobustness2PropertiesEXT.pNext");
_Static_assert(offsetof(VkPhysicalDeviceRobustness2PropertiesEXT, robustStorageBufferAccessSizeAlignment) == 16 && sizeof(((VkPhysicalDeviceRobustness2PropertiesEXT *)0)->robustStorageBufferAccessSizeAlignment) == 8, "Pinned VkPhysicalDeviceRobustness2PropertiesEXT.robustStorageBufferAccessSizeAlignment");
_Static_assert(offsetof(VkPhysicalDeviceRobustness2PropertiesEXT, robustUniformBufferAccessSizeAlignment) == 24 && sizeof(((VkPhysicalDeviceRobustness2PropertiesEXT *)0)->robustUniformBufferAccessSizeAlignment) == 8, "Pinned VkPhysicalDeviceRobustness2PropertiesEXT.robustUniformBufferAccessSizeAlignment");
_Static_assert(sizeof(VkPhysicalDeviceMaintenance5Properties) == 40 && _Alignof(VkPhysicalDeviceMaintenance5Properties) == 8, "Pinned VkPhysicalDeviceMaintenance5Properties ABI");
_Static_assert(offsetof(VkPhysicalDeviceMaintenance5Properties, sType) == 0 && sizeof(((VkPhysicalDeviceMaintenance5Properties *)0)->sType) == 4, "Pinned VkPhysicalDeviceMaintenance5Properties.sType");
_Static_assert(offsetof(VkPhysicalDeviceMaintenance5Properties, pNext) == 8 && sizeof(((VkPhysicalDeviceMaintenance5Properties *)0)->pNext) == 8, "Pinned VkPhysicalDeviceMaintenance5Properties.pNext");
_Static_assert(offsetof(VkPhysicalDeviceMaintenance5Properties, earlyFragmentMultisampleCoverageAfterSampleCounting) == 16 && sizeof(((VkPhysicalDeviceMaintenance5Properties *)0)->earlyFragmentMultisampleCoverageAfterSampleCounting) == 4, "Pinned VkPhysicalDeviceMaintenance5Properties.earlyFragmentMultisampleCoverageAfterSampleCounting");
_Static_assert(offsetof(VkPhysicalDeviceMaintenance5Properties, earlyFragmentSampleMaskTestBeforeSampleCounting) == 20 && sizeof(((VkPhysicalDeviceMaintenance5Properties *)0)->earlyFragmentSampleMaskTestBeforeSampleCounting) == 4, "Pinned VkPhysicalDeviceMaintenance5Properties.earlyFragmentSampleMaskTestBeforeSampleCounting");
_Static_assert(offsetof(VkPhysicalDeviceMaintenance5Properties, depthStencilSwizzleOneSupport) == 24 && sizeof(((VkPhysicalDeviceMaintenance5Properties *)0)->depthStencilSwizzleOneSupport) == 4, "Pinned VkPhysicalDeviceMaintenance5Properties.depthStencilSwizzleOneSupport");
_Static_assert(offsetof(VkPhysicalDeviceMaintenance5Properties, polygonModePointSize) == 28 && sizeof(((VkPhysicalDeviceMaintenance5Properties *)0)->polygonModePointSize) == 4, "Pinned VkPhysicalDeviceMaintenance5Properties.polygonModePointSize");
_Static_assert(offsetof(VkPhysicalDeviceMaintenance5Properties, nonStrictSinglePixelWideLinesUseParallelogram) == 32 && sizeof(((VkPhysicalDeviceMaintenance5Properties *)0)->nonStrictSinglePixelWideLinesUseParallelogram) == 4, "Pinned VkPhysicalDeviceMaintenance5Properties.nonStrictSinglePixelWideLinesUseParallelogram");
_Static_assert(offsetof(VkPhysicalDeviceMaintenance5Properties, nonStrictWideLinesUseParallelogram) == 36 && sizeof(((VkPhysicalDeviceMaintenance5Properties *)0)->nonStrictWideLinesUseParallelogram) == 4, "Pinned VkPhysicalDeviceMaintenance5Properties.nonStrictWideLinesUseParallelogram");
/** @brief Fill owned native payloads with distinct per-member values.
 * @param[out] core Nonnull exclusive core storage. @param[out] nodes Nonnull five-node storage.
 * @param[in] tags Borrowed recognized unique array[count], count0..5.
 * @param[in] count Accessible tag count. @note No allocation/retention; distinct owners are thread-safe. */
static inline void property_fixture_init(VkPhysicalDeviceProperties *core, property_data_t *nodes, const uint32_t *tags, size_t count) {
  assert(core && nodes && tags && count <= 5);
  memset(core, 0, sizeof(*core));
  memset(nodes, 0, 5 * sizeof(*nodes));
  (*core).apiVersion = (uint32_t)10;
  (*core).driverVersion = (uint32_t)13;
  (*core).vendorID = (uint32_t)16;
  (*core).deviceID = (uint32_t)19;
  (*core).deviceType = (VkPhysicalDeviceType)22;
  memset((*core).deviceName, 0, sizeof((*core).deviceName));
  memcpy((*core).deviceName, "fixture_6", sizeof("fixture_6"));
  (*core).pipelineCacheUUID[0] = (uint8_t)22;
  (*core).pipelineCacheUUID[1] = (uint8_t)23;
  (*core).pipelineCacheUUID[2] = (uint8_t)24;
  (*core).pipelineCacheUUID[3] = (uint8_t)25;
  (*core).pipelineCacheUUID[4] = (uint8_t)26;
  (*core).pipelineCacheUUID[5] = (uint8_t)27;
  (*core).pipelineCacheUUID[6] = (uint8_t)28;
  (*core).pipelineCacheUUID[7] = (uint8_t)29;
  (*core).pipelineCacheUUID[8] = (uint8_t)30;
  (*core).pipelineCacheUUID[9] = (uint8_t)31;
  (*core).pipelineCacheUUID[10] = (uint8_t)32;
  (*core).pipelineCacheUUID[11] = (uint8_t)33;
  (*core).pipelineCacheUUID[12] = (uint8_t)34;
  (*core).pipelineCacheUUID[13] = (uint8_t)35;
  (*core).pipelineCacheUUID[14] = (uint8_t)36;
  (*core).pipelineCacheUUID[15] = (uint8_t)37;
  (*core).limits.maxImageDimension1D = (uint32_t)31;
  (*core).limits.maxImageDimension2D = (uint32_t)34;
  (*core).limits.maxImageDimension3D = (uint32_t)37;
  (*core).limits.maxImageDimensionCube = (uint32_t)40;
  (*core).limits.maxImageArrayLayers = (uint32_t)43;
  (*core).limits.maxTexelBufferElements = (uint32_t)46;
  (*core).limits.maxUniformBufferRange = (uint32_t)49;
  (*core).limits.maxStorageBufferRange = (uint32_t)52;
  (*core).limits.maxPushConstantsSize = (uint32_t)55;
  (*core).limits.maxMemoryAllocationCount = (uint32_t)58;
  (*core).limits.maxSamplerAllocationCount = (uint32_t)61;
  (*core).limits.bufferImageGranularity = (VkDeviceSize)(UINT64_C(0x1234567800000000) + 19);
  (*core).limits.sparseAddressSpaceSize = (VkDeviceSize)(UINT64_C(0x1234567800000000) + 20);
  (*core).limits.maxBoundDescriptorSets = (uint32_t)70;
  (*core).limits.maxPerStageDescriptorSamplers = (uint32_t)73;
  (*core).limits.maxPerStageDescriptorUniformBuffers = (uint32_t)76;
  (*core).limits.maxPerStageDescriptorStorageBuffers = (uint32_t)79;
  (*core).limits.maxPerStageDescriptorSampledImages = (uint32_t)82;
  (*core).limits.maxPerStageDescriptorStorageImages = (uint32_t)85;
  (*core).limits.maxPerStageDescriptorInputAttachments = (uint32_t)88;
  (*core).limits.maxPerStageResources = (uint32_t)91;
  (*core).limits.maxDescriptorSetSamplers = (uint32_t)94;
  (*core).limits.maxDescriptorSetUniformBuffers = (uint32_t)97;
  (*core).limits.maxDescriptorSetUniformBuffersDynamic = (uint32_t)100;
  (*core).limits.maxDescriptorSetStorageBuffers = (uint32_t)103;
  (*core).limits.maxDescriptorSetStorageBuffersDynamic = (uint32_t)106;
  (*core).limits.maxDescriptorSetSampledImages = (uint32_t)109;
  (*core).limits.maxDescriptorSetStorageImages = (uint32_t)112;
  (*core).limits.maxDescriptorSetInputAttachments = (uint32_t)115;
  (*core).limits.maxVertexInputAttributes = (uint32_t)118;
  (*core).limits.maxVertexInputBindings = (uint32_t)121;
  (*core).limits.maxVertexInputAttributeOffset = (uint32_t)124;
  (*core).limits.maxVertexInputBindingStride = (uint32_t)127;
  (*core).limits.maxVertexOutputComponents = (uint32_t)130;
  (*core).limits.maxTessellationGenerationLevel = (uint32_t)133;
  (*core).limits.maxTessellationPatchSize = (uint32_t)136;
  (*core).limits.maxTessellationControlPerVertexInputComponents = (uint32_t)139;
  (*core).limits.maxTessellationControlPerVertexOutputComponents = (uint32_t)142;
  (*core).limits.maxTessellationControlPerPatchOutputComponents = (uint32_t)145;
  (*core).limits.maxTessellationControlTotalOutputComponents = (uint32_t)148;
  (*core).limits.maxTessellationEvaluationInputComponents = (uint32_t)151;
  (*core).limits.maxTessellationEvaluationOutputComponents = (uint32_t)154;
  (*core).limits.maxGeometryShaderInvocations = (uint32_t)157;
  (*core).limits.maxGeometryInputComponents = (uint32_t)160;
  (*core).limits.maxGeometryOutputComponents = (uint32_t)163;
  (*core).limits.maxGeometryOutputVertices = (uint32_t)166;
  (*core).limits.maxGeometryTotalOutputComponents = (uint32_t)169;
  (*core).limits.maxFragmentInputComponents = (uint32_t)172;
  (*core).limits.maxFragmentOutputAttachments = (uint32_t)175;
  (*core).limits.maxFragmentDualSrcAttachments = (uint32_t)178;
  (*core).limits.maxFragmentCombinedOutputResources = (uint32_t)181;
  (*core).limits.maxComputeSharedMemorySize = (uint32_t)184;
  (*core).limits.maxComputeWorkGroupCount[0] = (uint32_t)181;
  (*core).limits.maxComputeWorkGroupCount[1] = (uint32_t)182;
  (*core).limits.maxComputeWorkGroupCount[2] = (uint32_t)183;
  (*core).limits.maxComputeWorkGroupInvocations = (uint32_t)190;
  (*core).limits.maxComputeWorkGroupSize[0] = (uint32_t)187;
  (*core).limits.maxComputeWorkGroupSize[1] = (uint32_t)188;
  (*core).limits.maxComputeWorkGroupSize[2] = (uint32_t)189;
  (*core).limits.subPixelPrecisionBits = (uint32_t)196;
  (*core).limits.subTexelPrecisionBits = (uint32_t)199;
  (*core).limits.mipmapPrecisionBits = (uint32_t)202;
  (*core).limits.maxDrawIndexedIndexValue = (uint32_t)205;
  (*core).limits.maxDrawIndirectCount = (uint32_t)208;
  (*core).limits.maxSamplerLodBias = 68.25f;
  (*core).limits.maxSamplerAnisotropy = 69.25f;
  (*core).limits.maxViewports = (uint32_t)217;
  (*core).limits.maxViewportDimensions[0] = (uint32_t)214;
  (*core).limits.maxViewportDimensions[1] = (uint32_t)215;
  (*core).limits.viewportBoundsRange[0] = (float)217;
  (*core).limits.viewportBoundsRange[1] = (float)218;
  (*core).limits.viewportSubPixelBits = (uint32_t)226;
  (*core).limits.minMemoryMapAlignment = (size_t)(UINT64_C(0x1234567800000000) + 74);
  (*core).limits.minTexelBufferOffsetAlignment = (VkDeviceSize)(UINT64_C(0x1234567800000000) + 75);
  (*core).limits.minUniformBufferOffsetAlignment = (VkDeviceSize)(UINT64_C(0x1234567800000000) + 76);
  (*core).limits.minStorageBufferOffsetAlignment = (VkDeviceSize)(UINT64_C(0x1234567800000000) + 77);
  (*core).limits.minTexelOffset = -78;
  (*core).limits.maxTexelOffset = (uint32_t)244;
  (*core).limits.minTexelGatherOffset = -80;
  (*core).limits.maxTexelGatherOffset = (uint32_t)250;
  (*core).limits.minInterpolationOffset = 82.25f;
  (*core).limits.maxInterpolationOffset = 83.25f;
  (*core).limits.subPixelInterpolationOffsetBits = (uint32_t)259;
  (*core).limits.maxFramebufferWidth = (uint32_t)262;
  (*core).limits.maxFramebufferHeight = (uint32_t)265;
  (*core).limits.maxFramebufferLayers = (uint32_t)268;
  (*core).limits.framebufferColorSampleCounts = (VkSampleCountFlags)271;
  (*core).limits.framebufferDepthSampleCounts = (VkSampleCountFlags)274;
  (*core).limits.framebufferStencilSampleCounts = (VkSampleCountFlags)277;
  (*core).limits.framebufferNoAttachmentsSampleCounts = (VkSampleCountFlags)280;
  (*core).limits.maxColorAttachments = (uint32_t)283;
  (*core).limits.sampledImageColorSampleCounts = (VkSampleCountFlags)286;
  (*core).limits.sampledImageIntegerSampleCounts = (VkSampleCountFlags)289;
  (*core).limits.sampledImageDepthSampleCounts = (VkSampleCountFlags)292;
  (*core).limits.sampledImageStencilSampleCounts = (VkSampleCountFlags)295;
  (*core).limits.storageImageSampleCounts = (VkSampleCountFlags)298;
  (*core).limits.maxSampleMaskWords = (uint32_t)301;
  (*core).limits.timestampComputeAndGraphics = (VkBool32)1;
  (*core).limits.timestampPeriod = 100.25f;
  (*core).limits.maxClipDistances = (uint32_t)310;
  (*core).limits.maxCullDistances = (uint32_t)313;
  (*core).limits.maxCombinedClipAndCullDistances = (uint32_t)316;
  (*core).limits.discreteQueuePriorities = (uint32_t)319;
  (*core).limits.pointSizeRange[0] = (float)65;
  (*core).limits.pointSizeRange[1] = (float)66;
  (*core).limits.lineWidthRange[0] = (float)68;
  (*core).limits.lineWidthRange[1] = (float)69;
  (*core).limits.pointSizeGranularity = 107.25f;
  (*core).limits.lineWidthGranularity = 108.25f;
  (*core).limits.strictLines = (VkBool32)1;
  (*core).limits.standardSampleLocations = (VkBool32)0;
  (*core).limits.optimalBufferCopyOffsetAlignment = (VkDeviceSize)(UINT64_C(0x1234567800000000) + 111);
  (*core).limits.optimalBufferCopyRowPitchAlignment = (VkDeviceSize)(UINT64_C(0x1234567800000000) + 112);
  (*core).limits.nonCoherentAtomSize = (VkDeviceSize)(UINT64_C(0x1234567800000000) + 113);
  (*core).sparseProperties.residencyStandard2DBlockShape = (VkBool32)0;
  (*core).sparseProperties.residencyStandard2DMultisampleBlockShape = (VkBool32)1;
  (*core).sparseProperties.residencyStandard3DBlockShape = (VkBool32)0;
  (*core).sparseProperties.residencyAlignedMipSize = (VkBool32)1;
  (*core).sparseProperties.residencyNonResidentStrict = (VkBool32)0;
  for (size_t index = 0; index < count; index++) {
    switch(tags[index]) {
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_1_PROPERTIES:
      nodes[index].core11.sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_1_PROPERTIES;
      nodes[index].core11.deviceUUID[0] = (uint8_t)107;
      nodes[index].core11.deviceUUID[1] = (uint8_t)108;
      nodes[index].core11.deviceUUID[2] = (uint8_t)109;
      nodes[index].core11.deviceUUID[3] = (uint8_t)110;
      nodes[index].core11.deviceUUID[4] = (uint8_t)111;
      nodes[index].core11.deviceUUID[5] = (uint8_t)112;
      nodes[index].core11.deviceUUID[6] = (uint8_t)113;
      nodes[index].core11.deviceUUID[7] = (uint8_t)114;
      nodes[index].core11.deviceUUID[8] = (uint8_t)115;
      nodes[index].core11.deviceUUID[9] = (uint8_t)116;
      nodes[index].core11.deviceUUID[10] = (uint8_t)117;
      nodes[index].core11.deviceUUID[11] = (uint8_t)118;
      nodes[index].core11.deviceUUID[12] = (uint8_t)119;
      nodes[index].core11.deviceUUID[13] = (uint8_t)120;
      nodes[index].core11.deviceUUID[14] = (uint8_t)121;
      nodes[index].core11.deviceUUID[15] = (uint8_t)122;
      nodes[index].core11.driverUUID[0] = (uint8_t)110;
      nodes[index].core11.driverUUID[1] = (uint8_t)111;
      nodes[index].core11.driverUUID[2] = (uint8_t)112;
      nodes[index].core11.driverUUID[3] = (uint8_t)113;
      nodes[index].core11.driverUUID[4] = (uint8_t)114;
      nodes[index].core11.driverUUID[5] = (uint8_t)115;
      nodes[index].core11.driverUUID[6] = (uint8_t)116;
      nodes[index].core11.driverUUID[7] = (uint8_t)117;
      nodes[index].core11.driverUUID[8] = (uint8_t)118;
      nodes[index].core11.driverUUID[9] = (uint8_t)119;
      nodes[index].core11.driverUUID[10] = (uint8_t)120;
      nodes[index].core11.driverUUID[11] = (uint8_t)121;
      nodes[index].core11.driverUUID[12] = (uint8_t)122;
      nodes[index].core11.driverUUID[13] = (uint8_t)123;
      nodes[index].core11.driverUUID[14] = (uint8_t)124;
      nodes[index].core11.driverUUID[15] = (uint8_t)125;
      nodes[index].core11.deviceLUID[0] = (uint8_t)113;
      nodes[index].core11.deviceLUID[1] = (uint8_t)114;
      nodes[index].core11.deviceLUID[2] = (uint8_t)115;
      nodes[index].core11.deviceLUID[3] = (uint8_t)116;
      nodes[index].core11.deviceLUID[4] = (uint8_t)117;
      nodes[index].core11.deviceLUID[5] = (uint8_t)118;
      nodes[index].core11.deviceLUID[6] = (uint8_t)119;
      nodes[index].core11.deviceLUID[7] = (uint8_t)120;
      nodes[index].core11.deviceNodeMask = (uint32_t)373;
      nodes[index].core11.deviceLUIDValid = (VkBool32)1;
      nodes[index].core11.subgroupSize = (uint32_t)379;
      nodes[index].core11.subgroupSupportedStages = (VkShaderStageFlags)382;
      nodes[index].core11.subgroupSupportedOperations = (VkSubgroupFeatureFlags)385;
      nodes[index].core11.subgroupQuadOperationsInAllStages = (VkBool32)1;
      nodes[index].core11.pointClippingBehavior = (VkPointClippingBehavior)391;
      nodes[index].core11.maxMultiviewViewCount = (uint32_t)394;
      nodes[index].core11.maxMultiviewInstanceIndex = (uint32_t)397;
      nodes[index].core11.protectedNoFault = (VkBool32)1;
      nodes[index].core11.maxPerSetDescriptors = (uint32_t)403;
      nodes[index].core11.maxMemoryAllocationSize = (VkDeviceSize)(UINT64_C(0x1234567800000000) + 133);
      break;
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_2_PROPERTIES:
      nodes[index].core12.sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_2_PROPERTIES;
      nodes[index].core12.driverID = (VkDriverId)409;
      memset(nodes[index].core12.driverName, 0, sizeof(nodes[index].core12.driverName));
      memcpy(nodes[index].core12.driverName, "fixture_135", sizeof("fixture_135"));
      memset(nodes[index].core12.driverInfo, 0, sizeof(nodes[index].core12.driverInfo));
      memcpy(nodes[index].core12.driverInfo, "fixture_136", sizeof("fixture_136"));
      nodes[index].core12.conformanceVersion.major = (uint8_t)138;
      nodes[index].core12.conformanceVersion.minor = (uint8_t)139;
      nodes[index].core12.conformanceVersion.subminor = (uint8_t)140;
      nodes[index].core12.conformanceVersion.patch = (uint8_t)141;
      nodes[index].core12.denormBehaviorIndependence = (VkShaderFloatControlsIndependence)430;
      nodes[index].core12.roundingModeIndependence = (VkShaderFloatControlsIndependence)433;
      nodes[index].core12.shaderSignedZeroInfNanPreserveFloat16 = (VkBool32)1;
      nodes[index].core12.shaderSignedZeroInfNanPreserveFloat32 = (VkBool32)0;
      nodes[index].core12.shaderSignedZeroInfNanPreserveFloat64 = (VkBool32)1;
      nodes[index].core12.shaderDenormPreserveFloat16 = (VkBool32)0;
      nodes[index].core12.shaderDenormPreserveFloat32 = (VkBool32)1;
      nodes[index].core12.shaderDenormPreserveFloat64 = (VkBool32)0;
      nodes[index].core12.shaderDenormFlushToZeroFloat16 = (VkBool32)1;
      nodes[index].core12.shaderDenormFlushToZeroFloat32 = (VkBool32)0;
      nodes[index].core12.shaderDenormFlushToZeroFloat64 = (VkBool32)1;
      nodes[index].core12.shaderRoundingModeRTEFloat16 = (VkBool32)0;
      nodes[index].core12.shaderRoundingModeRTEFloat32 = (VkBool32)1;
      nodes[index].core12.shaderRoundingModeRTEFloat64 = (VkBool32)0;
      nodes[index].core12.shaderRoundingModeRTZFloat16 = (VkBool32)1;
      nodes[index].core12.shaderRoundingModeRTZFloat32 = (VkBool32)0;
      nodes[index].core12.shaderRoundingModeRTZFloat64 = (VkBool32)1;
      nodes[index].core12.maxUpdateAfterBindDescriptorsInAllPools = (uint32_t)481;
      nodes[index].core12.shaderUniformBufferArrayNonUniformIndexingNative = (VkBool32)1;
      nodes[index].core12.shaderSampledImageArrayNonUniformIndexingNative = (VkBool32)0;
      nodes[index].core12.shaderStorageBufferArrayNonUniformIndexingNative = (VkBool32)1;
      nodes[index].core12.shaderStorageImageArrayNonUniformIndexingNative = (VkBool32)0;
      nodes[index].core12.shaderInputAttachmentArrayNonUniformIndexingNative = (VkBool32)1;
      nodes[index].core12.robustBufferAccessUpdateAfterBind = (VkBool32)0;
      nodes[index].core12.quadDivergentImplicitLod = (VkBool32)1;
      nodes[index].core12.maxPerStageDescriptorUpdateAfterBindSamplers = (uint32_t)505;
      nodes[index].core12.maxPerStageDescriptorUpdateAfterBindUniformBuffers = (uint32_t)508;
      nodes[index].core12.maxPerStageDescriptorUpdateAfterBindStorageBuffers = (uint32_t)511;
      nodes[index].core12.maxPerStageDescriptorUpdateAfterBindSampledImages = (uint32_t)514;
      nodes[index].core12.maxPerStageDescriptorUpdateAfterBindStorageImages = (uint32_t)517;
      nodes[index].core12.maxPerStageDescriptorUpdateAfterBindInputAttachments = (uint32_t)520;
      nodes[index].core12.maxPerStageUpdateAfterBindResources = (uint32_t)523;
      nodes[index].core12.maxDescriptorSetUpdateAfterBindSamplers = (uint32_t)526;
      nodes[index].core12.maxDescriptorSetUpdateAfterBindUniformBuffers = (uint32_t)529;
      nodes[index].core12.maxDescriptorSetUpdateAfterBindUniformBuffersDynamic = (uint32_t)532;
      nodes[index].core12.maxDescriptorSetUpdateAfterBindStorageBuffers = (uint32_t)535;
      nodes[index].core12.maxDescriptorSetUpdateAfterBindStorageBuffersDynamic = (uint32_t)538;
      nodes[index].core12.maxDescriptorSetUpdateAfterBindSampledImages = (uint32_t)541;
      nodes[index].core12.maxDescriptorSetUpdateAfterBindStorageImages = (uint32_t)544;
      nodes[index].core12.maxDescriptorSetUpdateAfterBindInputAttachments = (uint32_t)547;
      nodes[index].core12.supportedDepthResolveModes = (VkResolveModeFlags)550;
      nodes[index].core12.supportedStencilResolveModes = (VkResolveModeFlags)553;
      nodes[index].core12.independentResolveNone = (VkBool32)1;
      nodes[index].core12.independentResolve = (VkBool32)0;
      nodes[index].core12.filterMinmaxSingleComponentFormats = (VkBool32)1;
      nodes[index].core12.filterMinmaxImageComponentMapping = (VkBool32)0;
      nodes[index].core12.maxTimelineSemaphoreValueDifference = (uint64_t)(UINT64_C(0x1234567800000000) + 187);
      nodes[index].core12.framebufferIntegerColorSampleCounts = (VkSampleCountFlags)571;
      break;
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_3_PROPERTIES:
      nodes[index].core13.sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_3_PROPERTIES;
      nodes[index].core13.minSubgroupSize = (uint32_t)574;
      nodes[index].core13.maxSubgroupSize = (uint32_t)577;
      nodes[index].core13.maxComputeWorkgroupSubgroups = (uint32_t)580;
      nodes[index].core13.requiredSubgroupSizeStages = (VkShaderStageFlags)583;
      nodes[index].core13.maxInlineUniformBlockSize = (uint32_t)586;
      nodes[index].core13.maxPerStageDescriptorInlineUniformBlocks = (uint32_t)589;
      nodes[index].core13.maxPerStageDescriptorUpdateAfterBindInlineUniformBlocks = (uint32_t)592;
      nodes[index].core13.maxDescriptorSetInlineUniformBlocks = (uint32_t)595;
      nodes[index].core13.maxDescriptorSetUpdateAfterBindInlineUniformBlocks = (uint32_t)598;
      nodes[index].core13.maxInlineUniformTotalSize = (uint32_t)601;
      nodes[index].core13.integerDotProduct8BitUnsignedAccelerated = (VkBool32)1;
      nodes[index].core13.integerDotProduct8BitSignedAccelerated = (VkBool32)0;
      nodes[index].core13.integerDotProduct8BitMixedSignednessAccelerated = (VkBool32)1;
      nodes[index].core13.integerDotProduct4x8BitPackedUnsignedAccelerated = (VkBool32)0;
      nodes[index].core13.integerDotProduct4x8BitPackedSignedAccelerated = (VkBool32)1;
      nodes[index].core13.integerDotProduct4x8BitPackedMixedSignednessAccelerated = (VkBool32)0;
      nodes[index].core13.integerDotProduct16BitUnsignedAccelerated = (VkBool32)1;
      nodes[index].core13.integerDotProduct16BitSignedAccelerated = (VkBool32)0;
      nodes[index].core13.integerDotProduct16BitMixedSignednessAccelerated = (VkBool32)1;
      nodes[index].core13.integerDotProduct32BitUnsignedAccelerated = (VkBool32)0;
      nodes[index].core13.integerDotProduct32BitSignedAccelerated = (VkBool32)1;
      nodes[index].core13.integerDotProduct32BitMixedSignednessAccelerated = (VkBool32)0;
      nodes[index].core13.integerDotProduct64BitUnsignedAccelerated = (VkBool32)1;
      nodes[index].core13.integerDotProduct64BitSignedAccelerated = (VkBool32)0;
      nodes[index].core13.integerDotProduct64BitMixedSignednessAccelerated = (VkBool32)1;
      nodes[index].core13.integerDotProductAccumulatingSaturating8BitUnsignedAccelerated = (VkBool32)0;
      nodes[index].core13.integerDotProductAccumulatingSaturating8BitSignedAccelerated = (VkBool32)1;
      nodes[index].core13.integerDotProductAccumulatingSaturating8BitMixedSignednessAccelerated = (VkBool32)0;
      nodes[index].core13.integerDotProductAccumulatingSaturating4x8BitPackedUnsignedAccelerated = (VkBool32)1;
      nodes[index].core13.integerDotProductAccumulatingSaturating4x8BitPackedSignedAccelerated = (VkBool32)0;
      nodes[index].core13.integerDotProductAccumulatingSaturating4x8BitPackedMixedSignednessAccelerated = (VkBool32)1;
      nodes[index].core13.integerDotProductAccumulatingSaturating16BitUnsignedAccelerated = (VkBool32)0;
      nodes[index].core13.integerDotProductAccumulatingSaturating16BitSignedAccelerated = (VkBool32)1;
      nodes[index].core13.integerDotProductAccumulatingSaturating16BitMixedSignednessAccelerated = (VkBool32)0;
      nodes[index].core13.integerDotProductAccumulatingSaturating32BitUnsignedAccelerated = (VkBool32)1;
      nodes[index].core13.integerDotProductAccumulatingSaturating32BitSignedAccelerated = (VkBool32)0;
      nodes[index].core13.integerDotProductAccumulatingSaturating32BitMixedSignednessAccelerated = (VkBool32)1;
      nodes[index].core13.integerDotProductAccumulatingSaturating64BitUnsignedAccelerated = (VkBool32)0;
      nodes[index].core13.integerDotProductAccumulatingSaturating64BitSignedAccelerated = (VkBool32)1;
      nodes[index].core13.integerDotProductAccumulatingSaturating64BitMixedSignednessAccelerated = (VkBool32)0;
      nodes[index].core13.storageTexelBufferOffsetAlignmentBytes = (VkDeviceSize)(UINT64_C(0x1234567800000000) + 229);
      nodes[index].core13.storageTexelBufferOffsetSingleTexelAlignment = (VkBool32)0;
      nodes[index].core13.uniformTexelBufferOffsetAlignmentBytes = (VkDeviceSize)(UINT64_C(0x1234567800000000) + 231);
      nodes[index].core13.uniformTexelBufferOffsetSingleTexelAlignment = (VkBool32)0;
      nodes[index].core13.maxBufferSize = (VkDeviceSize)(UINT64_C(0x1234567800000000) + 233);
      break;
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ROBUSTNESS_2_PROPERTIES_EXT:
      nodes[index].robustness.sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ROBUSTNESS_2_PROPERTIES_EXT;
      nodes[index].robustness.robustStorageBufferAccessSizeAlignment = (VkDeviceSize)(UINT64_C(0x1234567800000000) + 234);
      nodes[index].robustness.robustUniformBufferAccessSizeAlignment = (VkDeviceSize)(UINT64_C(0x1234567800000000) + 235);
      break;
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_5_PROPERTIES_KHR:
      nodes[index].maintenance.sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_5_PROPERTIES_KHR;
      nodes[index].maintenance.earlyFragmentMultisampleCoverageAfterSampleCounting = (VkBool32)0;
      nodes[index].maintenance.earlyFragmentSampleMaskTestBeforeSampleCounting = (VkBool32)1;
      nodes[index].maintenance.depthStencilSwizzleOneSupport = (VkBool32)0;
      nodes[index].maintenance.polygonModePointSize = (VkBool32)1;
      nodes[index].maintenance.nonStrictSinglePixelWideLinesUseParallelogram = (VkBool32)0;
      nodes[index].maintenance.nonStrictWideLinesUseParallelogram = (VkBool32)1;
      break;
    default: assert(0);
    }
  }
}
/** @brief Give private node copies borrowed forward links for one synchronous encoding.
 * @param[in,out] nodes Nonnull exclusive five-node storage. @param[in] tags Borrowed array[count].
 * @param[in] count Count0..5. @note No allocation, no retention; fixture thread only. */
static inline void property_nodes_link(property_data_t *nodes, const uint32_t *tags, size_t count) {
  for (size_t index = 0; index < count; index++) {
    void *next = index + 1 < count ? &nodes[index + 1] : NULL;
    switch(tags[index]) {
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_1_PROPERTIES: nodes[index].core11.sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_1_PROPERTIES; nodes[index].core11.pNext = next; break;
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_2_PROPERTIES: nodes[index].core12.sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_2_PROPERTIES; nodes[index].core12.pNext = next; break;
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_3_PROPERTIES: nodes[index].core13.sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_3_PROPERTIES; nodes[index].core13.pNext = next; break;
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ROBUSTNESS_2_PROPERTIES_EXT: nodes[index].robustness.sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ROBUSTNESS_2_PROPERTIES_EXT; nodes[index].robustness.pNext = next; break;
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_5_PROPERTIES_KHR: nodes[index].maintenance.sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_5_PROPERTIES_KHR; nodes[index].maintenance.pNext = next; break;
    default: assert(0);
    }
  }
}
#endif
