#!/usr/bin/env python3
"""Generate immutable guest headers and verify exact pinned renderer compatibility."""
from pathlib import Path
import subprocess
import sys
import tempfile

ProtocolCommit = "7157163d5fed65f0742542a8e77e5412dea6a4bc"


def main():
    """Return zero after offline generation and complete renderer comparison."""
    root = Path(__file__).resolve().parent.parent
    source = root / "submodules/venus_protocol"
    commit = subprocess.check_output(
        ["git", "-C", str(source), "rev-parse", "HEAD"], text=True
    ).strip()
    if commit != ProtocolCommit:
        raise RuntimeError("Venus generator differs from the audited immutable pin")
    if subprocess.check_output(["git", "-C", str(source), "status", "--porcelain"]):
        raise RuntimeError("Venus generator checkout contains unaudited local changes")
    driver = root / "build/venus_protocol"
    renderer = root / "build/venus_renderer_protocol"
    driver.mkdir(parents=True, exist_ok=True)
    renderer.mkdir(parents=True, exist_ok=True)
    # Generate privately: concurrent compilers must never see truncated headers.
    with tempfile.TemporaryDirectory(prefix="venus_protocol_", dir=root / "build") as temporary:
        staging = Path(temporary)
        staged_driver = staging / "driver"
        staged_renderer = staging / "renderer"
        staged_driver.mkdir()
        staged_renderer.mkdir()
        banner = staging / "banner"
        banner.write_text("/* This file is generated by venus-protocol git-7157163d. */\n\n")
        command = [sys.executable, str(source / "vn_protocol.py"), "--banner", str(banner)]
        subprocess.run(command + ["--outdir", str(staged_driver)], check=True)
        subprocess.run(command + ["--renderer", "--outdir", str(staged_renderer)], check=True)
        # Windows text-mode generators produce CRLF; receiver headers use LF.
        for directory in (staged_driver, staged_renderer):
            for path in directory.glob("*.h"):
                path.write_bytes(path.read_bytes().replace(b"\r\n", b"\n"))
        baseline = root / "submodules/virglrenderer/src/venus/venus-protocol"
        actual = {path.name for path in staged_renderer.glob("*.h")}
        expected = {path.name for path in baseline.glob("vn_*.h")}
        if actual != expected:
            raise RuntimeError("Generated renderer header set differs from the receiver")
        for name in sorted(actual):
            if (staged_renderer / name).read_bytes() != (baseline / name).read_bytes():
                raise RuntimeError("Generated renderer differs from receiver: " + name)
        for name in ("vulkan.h", "vulkan_core.h", "vk_platform.h"):
            if (source / "include/vulkan" / name).read_bytes() != (baseline / name).read_bytes():
                raise RuntimeError("Pinned Vulkan declaration differs from receiver: " + name)
        for staged_directory, destination in ((staged_driver, driver), (staged_renderer, renderer)):
            for path in staged_directory.glob("*.h"):
                target = destination / path.name
                if not target.exists() or target.read_bytes() != path.read_bytes():
                    path.replace(target)
        verified = staging / "verified"
        verified.write_text(ProtocolCommit + "\n")
        verified.replace(driver / "verified")
    print("Verified 39 exact receiver headers and generated 37 pinned guest headers")



if __name__ == "__main__":
    main()
