#!/usr/bin/env python3
"""Generate immutable guest headers and verify exact pinned renderer compatibility."""
from pathlib import Path
import subprocess
import sys

ProtocolCommit = "7157163d5fed65f0742542a8e77e5412dea6a4bc"


def main():
    """Return zero after offline generation and complete renderer comparison."""
    root = Path(__file__).resolve().parent.parent
    source = root / "submodules/venus_protocol"
    commit = subprocess.check_output(
        ["git", "-C", str(source), "rev-parse", "HEAD"], text=True
    ).strip()
    if commit != ProtocolCommit:
        raise RuntimeError("Venus generator differs from the audited immutable pin")
    if subprocess.check_output(["git", "-C", str(source), "status", "--porcelain"]):
        raise RuntimeError("Venus generator checkout contains unaudited local changes")
    driver = root / "build/venus_protocol"
    renderer = root / "build/venus_renderer_protocol"
    driver.mkdir(parents=True, exist_ok=True)
    renderer.mkdir(parents=True, exist_ok=True)
    banner = driver / "banner"
    banner.write_text(
        "/* This file is generated by venus-protocol git-7157163d. */\n\n"
    )
    command = [sys.executable, str(source / "vn_protocol.py"), "--banner", str(banner)]
    subprocess.run(command + ["--outdir", str(driver)], check=True)
    subprocess.run(command + ["--renderer", "--outdir", str(renderer)], check=True)
    baseline = root / "submodules/virglrenderer/src/venus/venus-protocol"
    actual = {path.name for path in renderer.glob("*.h")}
    expected = {path.name for path in baseline.glob("vn_*.h")}
    if actual != expected:
        raise RuntimeError("Generated renderer header set differs from the receiver")
    for name in sorted(actual):
        if (renderer / name).read_bytes() != (baseline / name).read_bytes():
            raise RuntimeError("Generated renderer differs from receiver: " + name)
    for name in ("vulkan.h", "vulkan_core.h", "vk_platform.h"):
        if (source / "include/vulkan" / name).read_bytes() != (baseline / name).read_bytes():
            raise RuntimeError("Pinned Vulkan declaration differs from receiver: " + name)
    print("Verified 39 exact receiver headers and generated 37 pinned guest headers")
    (driver / "verified").write_text(ProtocolCommit + "\n")


if __name__ == "__main__":
    main()
